INSERT OR IGNORE INTO terminology (id,canonical_key,language,script_form,transliteration,aliases_json,review_status) VALUES
('te-panchanga','panchanga','te','పంచాంగం','pañcāṅgam','[]','translation_review'),
('te-tithi','tithi','te','తిథి','tithi','[]','translation_review'),
('te-paksha','paksha','te','పక్షం','pakṣam','[]','translation_review'),
('te-yoga','yoga','te','యోగం','yōgam','[]','translation_review'),
('te-karana','karana','te','కరణం','karaṇam','[]','translation_review'),
('te-vara','vara','te','వారం','vāram','["వారము"]','translation_review'),
('te-mahadasha','mahadasha','te','మహాదశ','mahādaśa','[]','translation_review'),
('te-pratyantardasha','pratyantardasha','te','ప్రత్యంతర్దశ','pratyantardaśa','[]','translation_review'),
('te-ayanamsa','ayanamsa','te','అయనాంశం','ayanāṃśam','[]','translation_review'),
('te-sripati','sripati','te','శ్రీపతి భావ పద్ధతి','śrīpati bhāva paddhati','[]','translation_review'),
('te-sandhi','sandhi','te','భావ సంధి','bhāva sandhi','[]','translation_review'),
('te-uccha-bala','uchcha_bala','te','ఉచ్చ బలం','ucca balam','[]','translation_review'),
('te-dig-bala','dig_bala','te','దిగ్బలం','digbalam','[]','translation_review'),
('te-kala-bala','kala_bala','te','కాల బలం','kāla balam','[]','translation_review'),
('te-cheshta-bala','cheshta_bala','te','చేష్టా బలం','cēṣṭā balam','[]','translation_review'),
('te-drik-bala','drik_bala','te','దృక్ బలం','dṛk balam','[]','translation_review'),
('te-bhava-bala','bhava_bala','te','భావ బలం','bhāva balam','[]','translation_review'),
('te-graha-yuddha','graha_yuddha','te','గ్రహ యుద్ధం','graha yuddham','[]','translation_review'),
('te-sade-sati','sade_sati','te','ఏలినాటి శని','ēlināṭi śani','["సాడే సాతీ"]','translation_review'),
('te-dhaiya','dhaiya','te','అర్ధాష్టమ శని','ardhāṣṭama śani','["ఢైయా"]','translation_review'),
('te-uncertainty','uncertainty','te','అనిశ్చితి','aniściti','[]','translation_review'),
('te-evidence','evidence','te','ఆధారం','ādhāram','["సాక్ష్యం"]','translation_review'),
('te-retrograde','retrograde','te','వక్రగతి','vakragati','["వక్రం"]','translation_review'),
('te-sunrise','sunrise','te','సూర్యోదయం','sūryōdayam','[]','translation_review'),
('te-sunset','sunset','te','సూర్యాస్తమయం','sūryāstamayam','[]','translation_review');
