import type { Language } from "./types";

// Bilingual UI strings, adapted from the web client's table (src/ChatApp.tsx)
// so both surfaces speak with one voice.
export const STRINGS = {
  en: {
    tagline: "Your Jyotish companion. Share your birth details once — then just talk.",
    name: "Name",
    namePlaceholder: "Your name",
    dob: "Date of birth",
    tob: "Time of birth",
    pob: "Place of birth",
    pobPlaceholder: "Town, district, state",
    day: "Day",
    month: "Month",
    year: "Year",
    hour: "Hour",
    minute: "Min",
    months: ["January","February","March","April","May","June","July","August","September","October","November","December"],
    start: "Start the conversation",
    finding: "Finding your place…",
    continue: "Continue",
    back: "Back",
    privacy: "Your details are used only to calculate your chart. Create an account to keep them across devices.",
    editBirth: "Edit birth details",
    yourChart: "Your chart",
    birthDetails: "Birth details",
    anchors: "Anchors",
    lagna: "Lagna",
    moon: "Moon",
    currentDasha: "Current dasha",
    mahadasha: "Mahadasha",
    antardasha: "Antardasha",
    pratyantardasha: "Pratyantardasha",
    panchanga: "Birth panchanga",
    vara: "Vara",
    tithi: "Tithi",
    paksha: "Paksha",
    nakshatra: "Nakshatra",
    yoga: "Yoga",
    karana: "Karana",
    strength: "Planet strength",
    language: "Language",
    disclaimer: "Calculated evidence is deterministic and immutable; the assistant only narrates it. Astrology is a cultural practice, not scientific fact.",
    composer: "Ask about your chart…",
    thinking: "Thinking · checking the evidence ledger",
    genericError: "Something went wrong.",
    rateError: "Too many questions at once. Wait a minute and try again.",
    replyError: "The assistant could not reply.",
    placeError: "That place could not be found. Add district, state, or country.",
    placeAmbiguous: "A few places share that name — pick yours:",
    suggestions: [
      "What am I naturally good at?",
      "Help me understand school and learning.",
      "Explain my current phase in simple words.",
      "What can help me make better choices?",
      "What should I be careful about?",
    ],
    dailySuggestions: ["How is today for me?", "Anything to watch this week?"],
    padaShort: "P",
    account: "Account",
    signIn: "Sign in",
    signUp: "Create account",
    signOut: "Sign out",
    email: "Email",
    password: "Password (8+ characters)",
    noAccount: "New here? Create an account",
    haveAccount: "Already have an account? Sign in",
    signedInAs: "Signed in as",
    syncNote: "Your birth details and conversation are saved to your account.",
    authError: "Sign in failed. Check your email and password.",
    signupError: "Could not create the account. Try a different email or a longer password.",
    guestNote: "Continue without an account — details stay only on this device.",
    people: "People",
    addPerson: "+ Add another person",
    activeTag: "active",
    compare: "Compare charts",
    comparingWith: "Comparing with",
    clearCompare: "stop",
    compareAsk: "Check our traditional marriage compatibility.",
    deletePerson: "Remove",
    today: "Today's panchanga",
    sunrise: "Sunrise",
    sunset: "Sunset",
    rahuKaal: "Rahu kaal",
    chats: "Chats",
    newChat: "+ New chat",
    deleteChat: "Delete",
    emptyChat: "New chat",
    rename: "Rename",
    renamePrompt: "Chat name:",
    save: "Save",
    cancel: "Cancel",
    prashnaChip: "🔮 Prashna",
    prashnaBanner: "Prashna mode — ask your question now",
    prashnaOff: "cancel",
    muhurtaChip: "🕐 Good time for…",
    muhurtaTitle: "Find an auspicious time",
    muhurtaActivities: {
      marriage: "Marriage / engagement",
      travel: "Travel / journey",
      naming: "Naming / new beginning",
      contract: "Contract / signing / purchase",
    } as Record<string, string>,
    muhurtaAsk: "Find auspicious times in the next 5 days for",
    btrChip: "⏱ Rectify birth time",
    btrAsk: "Rectify my birth time.",
    moreChips: "More",
    fewerChips: "Fewer",
    shareChart: "Share chart link",
    shareCopied: "Link ready to share. Valid 30 days.",
    shareNeedsAccount: "Sign in to create share links.",
    reminders: "Daily morning reminder",
    remindersDesc: "A notification each morning with your panchanga, tara bala and rahu kaal.",
    remindersOn: "On · every morning at 7",
    remindersNeedsAccount: "Sign in to receive daily reminders.",
    remindersDenied: "Notifications are turned off. Enable them for Sahadeva in Settings.",
    remindersUnsupported: "Reminders need a physical device.",
    remindersUnconfigured: "Reminders require a build with push configured (EAS). Not available in this preview build.",
    remindersFailed: "Could not set up the reminder. Try again.",
    allPlacements: "Graha positions (D1)",
    planet: "Graha",
    signCol: "Sign",
    degreeCol: "Deg",
    nakCol: "Nakshatra",
    retro: "retro",
    dashaTimeline: "Vimshottari timeline",
    running: "running",
    yogasTitle: "Detected yogas",
    noYogas: "No classical yoga patterns were detected structurally.",
    sookshma: "Sookshma",
    rasiChart: "Rasi (D1)",
    navamsaChart: "Navamsa (D9)",
    southStyle: "South",
    northStyle: "North",
    judgmentTitle: "Topic judgment",
    judgmentTopics: {
      career: "Career",
      education: "Education",
      property: "Property",
      relationships: "Relationships",
      spirituality: "Spirituality",
    } as Record<string, string>,
    supporting: "What supports this",
    opposing: "What needs care",
    varga: "Varga",
    timing: "Timing",
    clarity: "Clarity",
    sourcesTitle: "Sources and honesty",
    citedRules: (n: number) => `${n} reviewed source rule(s) support this reading.`,
    unresolvedRules: (n: number) => `${n} traditional rule(s) still await expert review. Calculated facts remain visible.`,
    askInChat: "✨ Ask about this in chat",
    explainQ: {
      dasha: "Explain my current dasha periods simply — what do they mean for daily life?",
      placements: "Walk me through my planet placements one by one, in simple words.",
      timeline: "Explain my upcoming dasha periods for the next few years, simply.",
      yogas: "Explain the yogas detected in my chart in simple language.",
      chart: "Explain my rasi chart placements in simple words.",
      todayQ: "How is today for me?",
    },
    feedbackHelpful: "👍 Helpful",
    feedbackUnclear: "? Unclear",
    feedbackIncorrect: "⚑ Incorrect",
    feedbackSent: "Feedback sent for review.",
    followUp: "Follow up",
    followUpPrefill: "Explain this part of the reading in more detail: ",
    regenerate: "Regenerate",
    regenerateAsk: "Regenerate this complete profile reading.",
    shareReading: "↗ Share",
    dailyBrief: "Today's brief",
    todayTab: "Today",
    chatTab: "Chat",
    chartTab: "Chart",
    moreTab: "More",
    method: "How Sahadeva reasons",
    methodIntro: "The mobile app calls the same judgment API used by MCP and the web workspace. It does not maintain a separate interpretation engine.",
    researchBoundary: "Research-preview boundary",
    researchNote: "Astrology is a cultural interpretive practice, not scientific fact or professional advice. No single placement is an inevitable outcome.",
    loadingChart: "Calculating your chart…",
    chartUnavailable: "The chart could not be calculated right now.",
    needProfile: "Share your birth details in the Chat tab first.",
    confidence: "Confidence",
    signInFirst: "Sign in to sync across devices.",
    welcomeBack: "Namaste",
  },
  te: {
    tagline: "మీ జ్యోతిష సహచరుడు. జన్మ వివరాలు ఒక్కసారి ఇవ్వండి — ఆపై మాట్లాడండి.",
    name: "పేరు",
    namePlaceholder: "మీ పేరు",
    dob: "జన్మ తేదీ",
    tob: "జన్మ సమయం",
    pob: "జన్మ స్థలం",
    pobPlaceholder: "ఊరు, జిల్లా, రాష్ట్రం",
    day: "రోజు",
    month: "నెల",
    year: "సంవత్సరం",
    hour: "గంట",
    minute: "నిమి",
    months: ["జనవరి","ఫిబ్రవరి","మార్చి","ఏప్రిల్","మే","జూన్","జూలై","ఆగస్టు","సెప్టెంబర్","అక్టోబర్","నవంబర్","డిసెంబర్"],
    start: "సంభాషణ ప్రారంభించండి",
    finding: "మీ ఊరు వెతుకుతున్నాం…",
    continue: "కొనసాగించండి",
    back: "వెనుకకు",
    privacy: "వివరాలు జాతకం లెక్కించడానికి మాత్రమే. ఖాతా సృష్టిస్తే అన్ని పరికరాల్లో ఉంటాయి.",
    editBirth: "జన్మ వివరాలు మార్చండి",
    yourChart: "మీ జాతకం",
    birthDetails: "జన్మ వివరాలు",
    anchors: "మూల స్థానాలు",
    lagna: "లగ్నం",
    moon: "చంద్రుడు",
    currentDasha: "ప్రస్తుత దశ",
    mahadasha: "మహాదశ",
    antardasha: "అంతర్దశ",
    pratyantardasha: "ప్రత్యంతర్దశ",
    panchanga: "జన్మ పంచాంగం",
    vara: "వారం",
    tithi: "తిథి",
    paksha: "పక్షం",
    nakshatra: "నక్షత్రం",
    yoga: "యోగం",
    karana: "కరణం",
    strength: "గ్రహ బలం",
    language: "భాష",
    disclaimer: "లెక్కించిన సాక్ష్యం నిర్ణీతమైనది, మార్చలేనిది; సహాయకుడు దాన్ని వివరించడమే చేస్తాడు. జ్యోతిషం సాంస్కృతిక సంప్రదాయం, శాస్త్రీయంగా నిరూపితమైనది కాదు.",
    composer: "మీ జాతకం గురించి అడగండి…",
    thinking: "ఆలోచిస్తున్నాను · సాక్ష్యం పరిశీలిస్తున్నాను",
    genericError: "ఏదో తప్పు జరిగింది.",
    rateError: "ఒకేసారి ఎక్కువ ప్రశ్నలు వచ్చాయి. ఒక నిమిషం ఆగి మళ్ళీ ప్రయత్నించండి.",
    replyError: "సహాయకుడు సమాధానం ఇవ్వలేకపోయాడు.",
    placeError: "ఆ ఊరు దొరకలేదు. జిల్లా, రాష్ట్రం లేదా దేశం కూడా రాయండి.",
    placeAmbiguous: "ఆ పేరుతో కొన్ని ఊర్లు ఉన్నాయి — మీది ఎంచుకోండి:",
    suggestions: [
      "నాకు సహజంగా ఏ విషయాలు బాగా వస్తాయి?",
      "చదువు గురించి సులభంగా వివరించండి.",
      "నా ప్రస్తుత కాలాన్ని సులభమైన మాటల్లో చెప్పండి.",
      "మంచి నిర్ణయాలు తీసుకోవడానికి ఏమి సహాయపడుతుంది?",
      "నేను దేని విషయంలో జాగ్రత్తగా ఉండాలి?",
    ],
    dailySuggestions: ["ఈ రోజు నాకు ఎలా ఉంటుంది?", "ఈ వారం జాగ్రత్తలు ఏమైనా ఉన్నాయా?"],
    padaShort: "పా",
    account: "ఖాతా",
    signIn: "సైన్ ఇన్",
    signUp: "ఖాతా సృష్టించండి",
    signOut: "సైన్ అవుట్",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్ (8+ అక్షరాలు)",
    noAccount: "కొత్తవారా? ఖాతా సృష్టించండి",
    haveAccount: "ఖాతా ఉందా? సైన్ ఇన్ చేయండి",
    signedInAs: "సైన్ ఇన్ అయినది",
    syncNote: "మీ జన్మ వివరాలు, సంభాషణ మీ ఖాతాలో భద్రంగా ఉంటాయి.",
    authError: "సైన్ ఇన్ కాలేదు. ఇమెయిల్, పాస్‌వర్డ్ చూసుకోండి.",
    signupError: "ఖాతా సృష్టించలేకపోయాం. వేరే ఇమెయిల్ లేదా పొడవైన పాస్‌వర్డ్ ప్రయత్నించండి.",
    guestNote: "ఖాతా లేకుండా కొనసాగండి — వివరాలు ఈ పరికరంలో మాత్రమే ఉంటాయి.",
    people: "వ్యక్తులు",
    addPerson: "+ మరో వ్యక్తిని చేర్చండి",
    activeTag: "ప్రస్తుతం",
    compare: "జాతకాలు పోల్చండి",
    comparingWith: "పోలిక:",
    clearCompare: "ఆపండి",
    compareAsk: "మా సాంప్రదాయ వివాహ పొంతన చూడండి.",
    deletePerson: "తొలగించండి",
    today: "నేటి పంచాంగం",
    sunrise: "సూర్యోదయం",
    sunset: "సూర్యాస్తమయం",
    rahuKaal: "రాహుకాలం",
    chats: "సంభాషణలు",
    newChat: "+ కొత్త సంభాషణ",
    deleteChat: "తొలగించండి",
    emptyChat: "కొత్త సంభాషణ",
    rename: "పేరు మార్చండి",
    renamePrompt: "సంభాషణ పేరు:",
    save: "సేవ్ చేయండి",
    cancel: "రద్దు",
    prashnaChip: "🔮 ప్రశ్న",
    prashnaBanner: "ప్రశ్న మోడ్ — ఇప్పుడు మీ ప్రశ్న అడగండి",
    prashnaOff: "రద్దు",
    muhurtaChip: "🕐 మంచి సమయం…",
    muhurtaTitle: "శుభ ముహూర్తం వెతకండి",
    muhurtaActivities: {
      marriage: "వివాహం / నిశ్చితార్థం",
      travel: "ప్రయాణం",
      naming: "నామకరణం / కొత్త ఆరంభం",
      contract: "ఒప్పందం / సంతకం / కొనుగోలు",
    } as Record<string, string>,
    muhurtaAsk: "వచ్చే 5 రోజుల్లో శుభ సమయాలు చెప్పండి:",
    btrChip: "⏱ జనన సమయ సవరణ",
    btrAsk: "Rectify my birth time.",
    moreChips: "మరిన్ని",
    fewerChips: "తక్కువ",
    shareChart: "జాతకం లింక్ పంచుకోండి",
    shareCopied: "లింక్ సిద్ధం! 30 రోజులు చెల్లుతుంది.",
    shareNeedsAccount: "లింక్ కోసం సైన్ ఇన్ చేయండి.",
    reminders: "రోజువారీ ఉదయపు రిమైండర్",
    remindersDesc: "ప్రతి ఉదయం పంచాంగం, తారా బలం, రాహుకాలంతో నోటిఫికేషన్.",
    remindersOn: "ఆన్ · ప్రతి ఉదయం 7 గంటలకు",
    remindersNeedsAccount: "రోజువారీ రిమైండర్ల కోసం సైన్ ఇన్ చేయండి.",
    remindersDenied: "నోటిఫికేషన్లు ఆఫ్‌లో ఉన్నాయి. సెట్టింగ్స్‌లో సహదేవకు అనుమతించండి.",
    remindersUnsupported: "రిమైండర్లకు భౌతిక పరికరం అవసరం.",
    remindersUnconfigured: "రిమైండర్లకు పుష్ కాన్ఫిగర్ చేసిన బిల్డ్ (EAS) అవసరం. ఈ ప్రివ్యూలో అందుబాటులో లేదు.",
    remindersFailed: "రిమైండర్ సెటప్ కాలేదు. మళ్లీ ప్రయత్నించండి.",
    allPlacements: "గ్రహ స్థానాలు (D1)",
    planet: "గ్రహం",
    signCol: "రాశి",
    degreeCol: "డిగ్రీ",
    nakCol: "నక్షత్రం",
    retro: "వక్రం",
    dashaTimeline: "వింశోత్తరి దశా క్రమం",
    running: "నడుస్తోంది",
    yogasTitle: "గుర్తించిన యోగాలు",
    noYogas: "నిర్మాణాత్మకంగా ఏ శాస్త్రీయ యోగం గుర్తించబడలేదు.",
    sookshma: "సూక్ష్మ దశ",
    rasiChart: "రాశి చక్రం (D1)",
    navamsaChart: "నవాంశ (D9)",
    southStyle: "దక్షిణ",
    northStyle: "ఉత్తర",
    judgmentTitle: "అంశ నిర్ణయం",
    judgmentTopics: {
      career: "వృత్తి",
      education: "విద్య",
      property: "ఆస్తి",
      relationships: "సంబంధాలు",
      spirituality: "ఆధ్యాత్మికం",
    } as Record<string, string>,
    supporting: "అనుకూల సాక్ష్యం",
    opposing: "జాగ్రత్త అవసరమైనవి",
    varga: "వర్గ",
    timing: "కాలం",
    clarity: "స్పష్టత",
    sourcesTitle: "మూలాలు, నిజాయితీ",
    citedRules: (n: number) => `${n} సమీక్షించిన శాస్త్ర నియమాలు ఈ రీడింగ్‌కు ఆధారం.`,
    unresolvedRules: (n: number) => `${n} సాంప్రదాయ నియమాలు ఇంకా నిపుణుల సమీక్షలో ఉన్నాయి. లెక్కించిన వాస్తవాలు కనిపిస్తూనే ఉంటాయి.`,
    askInChat: "✨ చాట్‌లో అడగండి",
    explainQ: {
      dasha: "నా ప్రస్తుత దశలను సరళంగా వివరించండి — రోజువారీ జీవితానికి అర్థం ఏమిటి?",
      placements: "నా గ్రహ స్థానాలను ఒక్కొక్కటిగా సులభమైన మాటల్లో చెప్పండి.",
      timeline: "రాబోయే కొన్నేళ్ల నా దశలను సరళంగా వివరించండి.",
      yogas: "నా జాతకంలోని యోగాలను సులభమైన భాషలో వివరించండి.",
      chart: "నా రాశి చక్రంలోని గ్రహ స్థానాలను సులభంగా వివరించండి.",
      todayQ: "ఈ రోజు నాకు ఎలా ఉంటుంది?",
    },
    feedbackHelpful: "👍 ఉపయోగకరం",
    feedbackUnclear: "? అస్పష్టం",
    feedbackIncorrect: "⚑ తప్పు",
    feedbackSent: "ఫీడ్‌బ్యాక్ సమీక్షకు పంపబడింది.",
    followUp: "ఫాలో-అప్",
    followUpPrefill: "ఈ రీడింగ్‌లో ఈ విషయం గురించి మరింత వివరంగా చెప్పండి: ",
    regenerate: "మళ్లీ రూపొందించు",
    regenerateAsk: "ఈ సంపూర్ణ జాతక రీడింగ్‌ను మళ్లీ రూపొందించండి.",
    shareReading: "↗ పంచుకోండి",
    dailyBrief: "నేటి సంక్షిప్తం",
    todayTab: "ఈ రోజు",
    chatTab: "చాట్",
    chartTab: "జాతకం",
    moreTab: "మరిన్ని",
    method: "సహదేవ ఎలా ఆలోచిస్తాడు",
    methodIntro: "మొబైల్ యాప్ MCP, వెబ్ వేదిక ఉపయోగించే అదే నిర్ణయ API-ని పిలుస్తుంది. ప్రత్యేక వ్యాఖ్యాన ఇంజిన్ లేదు.",
    researchBoundary: "పరిశోధన-ప్రివ్యూ హద్దు",
    researchNote: "జ్యోతిషం సాంస్కృతిక సంప్రదాయం, శాస్త్రీయ నిజం లేదా వృత్తిపరమైన సలహా కాదు. ఏ ఒక్క గ్రహ స్థానం అనివార్య ఫలితం కాదు.",
    loadingChart: "మీ జాతకం లెక్కిస్తున్నాం…",
    chartUnavailable: "ప్రస్తుతం జాతకం లెక్కించలేకపోయాం.",
    needProfile: "ముందుగా చాట్ ట్యాబ్‌లో జన్మ వివరాలు ఇవ్వండి.",
    confidence: "విశ్వసనీయత",
    signInFirst: "అన్ని పరికరాల్లో సమకాలీకరించడానికి సైన్ ఇన్ చేయండి.",
    welcomeBack: "నమస్తే",
  },
} as const;

export type Strings = (typeof STRINGS)[Language];

export function getStrings(language: Language): Strings {
  return STRINGS[language] ?? STRINGS.en;
}
