import type {ChartResult,GrahaName} from "./schema";
import {projectAyanamsa,type AyanamsaId} from "./multiAyanamsa";
import {JUDGMENT_TOPIC_CONFIG,type JudgmentTopic} from "./judgmentTopics";

const LORDS:GrahaName[]=["Mars","Venus","Mercury","Moon","Sun","Mercury","Venus","Mars","Jupiter","Saturn","Saturn","Jupiter"];
export function compareConventions(chart:ChartResult,topic:JudgmentTopic,ids:AyanamsaId[]=["lahiri","krishnamurti","raman"]){
  const cfg=JUDGMENT_TOPIC_CONFIG[topic],variants=ids.map(id=>{const projection=projectAyanamsa(chart,id),lagna=projection.placements.find(p=>p.name==="Lagna")!,topicSign=(lagna.sign+cfg.house-1)%12,lord=LORDS[topicSign],anchors=[lord,...cfg.karakas.filter(name=>name!==lord)].map(name=>{const p=projection.placements.find(row=>row.name===name)!;return{name,sign:p.sign,signName:p.signName,house:p.houseFromLagna,nakshatra:p.nakshatra,pada:p.pada};});return{id,name:projection.selected.name,validation:projection.selected.validation,lagna:{sign:lagna.sign,signName:lagna.signName},topicHouse:cfg.house,topicSign,lord,anchors,boundaryChanges:projection.boundaryChangesFromLahiri};}),base=variants[0],changes=variants.slice(1).map(v=>({id:v.id,lagnaChanged:v.lagna.sign!==base.lagna.sign,lordChanged:v.lord!==base.lord,anchorChanges:v.anchors.flatMap(anchor=>{const original=base.anchors.find(row=>row.name===anchor.name);return !original||original.sign!==anchor.sign||original.house!==anchor.house||original.nakshatra!==anchor.nakshatra?[{name:anchor.name,from:original,to:anchor}]:[]})})),material=changes.some(row=>row.lagnaChanged||row.lordChanged||row.anchorChanges.length>0);
  return{schemaVersion:"sahadeva-convention-comparison-1",topic,selectedBaseline:"lahiri",variants,judgmentChangeAnalysis:{status:material?"material-anchor-change-review-required":"structurally-stable-at-tested-boundaries",material,changes,notice:material?"At least one topic anchor changes. Do not reuse the Lahiri judgment under that convention; recompute every dependent Varga, strength and Dasha after its engine is validated.":"Tested sign, house and Nakshatra anchors remain stable. This does not prove interpretive traditions agree."},traditionBoundary:{status:"not-silently-mixed",notice:"This compares ayanāṃśa calculation conventions only. Parāśari, Jaimini, KP and Western interpretive rules require separate reviewed rule packs."},safety:{status:"research-preview",notice:"Non-Lahiri projections are boundary diagnostics, not production-certified alternative charts."}};
}
