import { SIGNS } from "./constants";
import { calculateJaimini } from "./jaimini";
import type { ChartResult, GrahaName } from "./schema";

const LORDS:GrahaName[]=["Mars","Venus","Mercury","Moon","Sun","Mercury","Venus","Mars","Jupiter","Saturn","Saturn","Jupiter"];
const OWN:Partial<Record<GrahaName,number[]>>={Sun:[4],Moon:[3],Mars:[0,7],Mercury:[2,5],Jupiter:[8,11],Venus:[1,6],Saturn:[9,10]};
const EXALT:Partial<Record<GrahaName,number>>={Sun:0,Moon:1,Mars:9,Mercury:5,Jupiter:3,Venus:11,Saturn:6};
const DEITIES:Record<string,string[]>={Sun:["Shiva"],Moon:["Gauri"],Mars:["Skanda","Hanuman","Narasimha"],Mercury:["Vishnu"],Jupiter:["Sambashiva","Vamana"],Venus:["Lakshmi"],Saturn:["Narayana"],Rahu:["Durga"],Ketu:["Ganapati","Matsya"]};
const SOURCE={work:"Vedic Remedies in Astrology",author:"Sanjay Rath",sections:["1.12 Determination of deity","1.12.1 Ista Devata & Dharma Devata","1.12.2 Palan Karta","1.12.3 Guru Devata","1.12.4 Kula Devata"],reviewStatus:"parsed-source-awaiting-independent-rule-review"};
export type DevataLineageId="rath-eight-karaka-reversed-rahu"|"seven-karaka-comparative";
export const DEVATA_LINEAGES:Record<DevataLineageId,{label:string;supported:boolean;karakaScheme:string;reviewStatus:string}>={"rath-eight-karaka-reversed-rahu":{label:"Rath eight-Chara-Karaka method with reversed Rahu",supported:true,karakaScheme:"eight-karaka with reversed Rahu",reviewStatus:"structural-awaiting-independent-review"},"seven-karaka-comparative":{label:"Seven-Chara-Karaka comparative preset",supported:false,karakaScheme:"seven-karaka",reviewStatus:"withheld-no-approved-devata-rule-mapping"}};
type Candidate={planet:string;reason:string;priority:number;degree:number;d9Sign:number};
const rashiAspect=(from:number,to:number)=>{const movable=[0,3,6,9].includes(from),fixed=[1,4,7,10].includes(from),dual=[2,5,8,11].includes(from);return movable?[1,4,7,10].includes(to)&&to!==(from+1)%12:fixed?[0,3,6,9].includes(to)&&to!==(from+11)%12:dual&&[2,5,8,11].includes(to)&&from!==to;};
function rankCandidate(chart:ChartResult,planet:GrahaName,d9Sign:number,reason:string):Candidate{const placement=chart.placements.find(row=>row.name===planet),priority=EXALT[planet]===d9Sign?3:OWN[planet]?.includes(d9Sign)?2:1;return{planet,reason,priority,degree:placement?.degree??0,d9Sign};}
function strongestInfluence(chart:ChartResult,targetSign:number){const d9=chart.advanced.vargas.D9,occupants=d9.filter(row=>row.name!=="Lagna"&&row.sign===targetSign).map(row=>rankCandidate(chart,row.name,targetSign,"occupies the target Navamsha sign"));if(occupants.length)return{selectionMethod:"occupant",candidates:occupants.sort((a,b)=>b.priority-a.priority||b.degree-a.degree),selected:occupants.sort((a,b)=>b.priority-a.priority||b.degree-a.degree)[0]};const aspectors=d9.filter(row=>row.name!=="Lagna"&&rashiAspect(row.sign,targetSign)).map(row=>rankCandidate(chart,row.name,row.sign,"Jaimini Rashi Drishti to the target sign"));if(aspectors.length)return{selectionMethod:"rashi-aspect",candidates:aspectors.sort((a,b)=>b.priority-a.priority||b.degree-a.degree),selected:aspectors.sort((a,b)=>b.priority-a.priority||b.degree-a.degree)[0]};const lord=LORDS[targetSign];return{selectionMethod:"sign-lord",candidates:[rankCandidate(chart,lord,targetSign,"lords the target sign; no occupant or Rashi aspector")],selected:rankCandidate(chart,lord,targetSign,"lords the target sign; no occupant or Rashi aspector")};}
function result(chart:ChartResult,label:string,anchorSign:number,offset:number){const targetSign=(anchorSign+offset-1)%12,influence=strongestInfluence(chart,targetSign);return{label,anchorSign,anchorSignName:SIGNS[anchorSign],houseOffset:offset,targetSign,targetSignName:SIGNS[targetSign],...influence,deityCandidates:DEITIES[influence.selected.planet]??[],interpretationStatus:"traditional-candidate-not-exclusive-identification"};}

export function calculateDevataProfile(chart:ChartResult,options:{lineage?:DevataLineageId}={}){const lineage=options.lineage||"rath-eight-karaka-reversed-rahu",preset=DEVATA_LINEAGES[lineage];if(!preset?.supported)throw new Error(`Devata lineage '${lineage}' is not approved for calculation`);const jaimini=calculateJaimini(chart),eight=jaimini.charaKarakas.eightKarakaWithReversedRahu,ak=eight.find(row=>row.karaka==="Atmakaraka")!,amk=eight.find(row=>row.karaka==="Amatyakaraka")!,bk=eight.find(row=>row.karaka==="Bhratrikaraka")!,d9=chart.advanced.vargas.D9,d20=chart.advanced.vargas.D20,akD9=d9.find(row=>row.name===ak.name)!,amkD9=d9.find(row=>row.name===amk.name)!,bkD9=d9.find(row=>row.name===bk.name)!,d20Lagna=d20.find(row=>row.name==="Lagna");return{schemaVersion:"sahadeva-devata-profile-2",status:"structural-research-preview",lineage:{selected:lineage,preset,mixingAllowed:false},convention:{karakaScheme:preset.karakaScheme,karakamsha:"Navamsha sign occupied by Atmakaraka",influenceOrder:["occupants","Jaimini Rashi Drishti","sign lord"],tieBreak:["exaltation","own sign","higher D1 degree"],source:SOURCE},anchors:{atmakaraka:ak,amatyakaraka:amk,bhratrikaraka:bk,karakamshaSign:akD9.sign,karakamshaSignName:SIGNS[akD9.sign]},ishtaDevata:result(chart,"Ista Devata",akD9.sign,12),dharmaDevata:result(chart,"Dharma Devata",akD9.sign,9),palanaDevata:result(chart,"Palana Devata",amkD9.sign,6),guruDevata:{...result(chart,"Guru Devata",bkD9.sign,1),bhratrikaraka:bk.name,notice:"The Bhratrikaraka's Navamsha sign and its conjunctions/aspects identify the traditional teacher stream; this is not a claim about a specific living guru."},kulaDevata:d20Lagna?{...result(chart,"Kula Devata",d20Lagna.sign,2),varga:"D20"}:{status:"unavailable",notice:"D20 Lagna is unavailable."},birthTimeSensitivity:{minutes:chart.input.birthTimeAccuracyMinutes,sensitive:true,notice:"Navamsha and especially D20 anchors can change with birth-time error. Recalculate after rectification before treating these candidates as stable."},safety:{notACommand:true,notice:"These are lineage-specific symbolic deity candidates, not proof of faith, initiation, obligation, or a uniquely correct deity. Preserve the user's existing tradition and consult a qualified teacher before mantra or ritual practice.",prohibited:["initiation-only mantra prescription","claiming a deity is angry","costly ritual pressure","replacing health or professional care"]}};}
