import { SIGNS } from "./constants";
import type { ChartResult, GrahaName } from "./schema";

const LORDS:GrahaName[]=["Mars","Venus","Mercury","Moon","Sun","Mercury","Venus","Mars","Jupiter","Saturn","Saturn","Jupiter"];
const MANGAL_HOUSES=new Set([1,2,4,7,8,12]),CLASSICAL=["Sun","Moon","Mars","Mercury","Jupiter","Venus","Saturn"] as const,PLANETS_BESIDE_MOON=new Set(["Mars","Mercury","Jupiter","Venus","Saturn"]),MALEFICS=new Set(["Mars","Saturn","Rahu","Ketu"]);
const KAAL_SARPA_TYPES=["Ananta","Kulik","Vasuki","Shankhapal","Padma","Mahapadma","Takshak","Karkotak","Shankhachud","Ghatak","Vishdhar","Sheshnag"];
const norm=(value:number)=>((value%360)+360)%360,angular=(a:number,b:number)=>Math.min(norm(a-b),norm(b-a)),house=(origin:number,target:number)=>((target-origin+12)%12)+1;
const severity=(points:number):"none"|"low"|"moderate"|"high"=>points<=0?"none":points===1?"low":points===2?"moderate":"high";

export const DOSHA_RULEBOOK={id:"sahadeva-dosha-seed",version:"0.1.0",reviewStatus:"draft-unreviewed",sourceKeys:["dosha-seed:mangal:awaiting-review","dosha-seed:kaal-sarpa:awaiting-review","dosha-seed:kemadruma:awaiting-review","dosha-seed:pitru-candidate:awaiting-review"],notice:"Regional definitions and cancellation rules vary. These transparent structural tests await passage-level expert review."} as const;

export function calculateDoshas(chart:ChartResult){
  const lagna=chart.placements.find((item)=>item.name==="Lagna")!,moon=chart.placements.find((item)=>item.name==="Moon")!,mars=chart.placements.find((item)=>item.name==="Mars")!,sun=chart.placements.find((item)=>item.name==="Sun")!,rahu=chart.placements.find((item)=>item.name==="Rahu")!,ketu=chart.placements.find((item)=>item.name==="Ketu")!;
  const dignity=(name:GrahaName)=>chart.advanced.dignities.find((item)=>item.name===name),aspect=(from:GrahaName,to:GrahaName)=>chart.advanced.aspects.some((item)=>item.from===from&&item.to===to);
  const mangalRefs=(["Lagna","Moon","Venus"] as GrahaName[]).map((reference)=>{const origin=chart.placements.find((item)=>item.name===reference)!,value=house(origin.sign,mars.sign);return{reference,house:value,triggered:MANGAL_HOUSES.has(value)};}),mangalHits=mangalRefs.filter((item)=>item.triggered).length,mangalMitigations=[...(dignity("Mars")?.dignity==="own-sign"||dignity("Mars")?.dignity==="exalted"?[{rule:"mars-dignity",applies:true,evidence:`Mars is ${dignity("Mars")?.dignity}`}]:[]),...(aspect("Jupiter","Mars")?[{rule:"jupiter-aspect",applies:true,evidence:"Jupiter has Graha Drishti to Mars"}]:[])],mangalEffective=Math.max(0,mangalHits-Math.min(1,mangalMitigations.length));
  const nodeArc=(planetLongitude:number)=>norm(planetLongitude-rahu.longitude),forward=CLASSICAL.filter((name)=>{const p=chart.placements.find((item)=>item.name===name)!;return nodeArc(p.longitude)<=180.0001;}),backward=CLASSICAL.filter((name)=>{const p=chart.placements.find((item)=>item.name===name)!;return nodeArc(p.longitude)>=179.9999;}),contained=forward.length>=backward.length?forward:backward,allContained=contained.length===7,nodeConjunctions=CLASSICAL.filter((name)=>angular(chart.placements.find((item)=>item.name===name)!.longitude,rahu.longitude)<3||angular(chart.placements.find((item)=>item.name===name)!.longitude,ketu.longitude)<3),rahuHouse=house(lagna.sign,rahu.sign),kaalMitigations=[...(nodeConjunctions.length?[{rule:"node-boundary-conjunction",applies:true,evidence:`Boundary conjunctions: ${nodeConjunctions.join(", ")}`}]:[]),...(chart.placements.some((item)=>["Jupiter","Venus"].includes(item.name)&&[1,4,7,10].includes(house(lagna.sign,item.sign)))?[{rule:"benefic-kendra",applies:true,evidence:"Jupiter or Venus occupies a Kendra from Lagna"}]:[])];
  const adjacent=chart.placements.filter((item)=>PLANETS_BESIDE_MOON.has(item.name)&&[2,12].includes(house(moon.sign,item.sign))),kemadrumaPrimary=adjacent.length===0,kendraFromMoon=chart.placements.filter((item)=>PLANETS_BESIDE_MOON.has(item.name)&&[1,4,7,10].includes(house(moon.sign,item.sign))),moonKendra=[1,4,7,10].includes(house(lagna.sign,moon.sign)),kemadrumaCancellations=[...(kendraFromMoon.length?[{rule:"planet-kendra-from-moon",applies:true,evidence:kendraFromMoon.map((item)=>item.name).join(", ")}]:[]),...(moonKendra?[{rule:"moon-kendra-from-lagna",applies:true,evidence:`Moon is in house ${house(lagna.sign,moon.sign)} from Lagna`}]:[])],kemadrumaEffective=kemadrumaPrimary&&kemadrumaCancellations.length===0;
  const ninthSign=(lagna.sign+8)%12,ninthLord=LORDS[ninthSign],ninthLordPlacement=chart.placements.find((item)=>item.name===ninthLord)!,pitruEvidence=[...(angular(sun.longitude,rahu.longitude)<=8?["Sun conjunct Rahu within 8°"]:[]),...(angular(sun.longitude,ketu.longitude)<=8?["Sun conjunct Ketu within 8°"]:[]),...(angular(sun.longitude,chart.placements.find((item)=>item.name==="Saturn")!.longitude)<=8?["Sun conjunct Saturn within 8°"]:[]),...chart.placements.filter((item)=>MALEFICS.has(item.name)&&house(lagna.sign,item.sign)===9).map((item)=>`${item.name} occupies the 9th whole-sign house`),...(dignity(ninthLord)?.dignity==="debilitated"?[`9th lord ${ninthLord} is debilitated`]:[])],pitruMitigations=[...(aspect("Jupiter","Sun")?[{rule:"jupiter-aspects-sun",applies:true,evidence:"Jupiter aspects Sun"}]:[]),...(aspect("Jupiter",ninthLord)?[{rule:"jupiter-aspects-ninth-lord",applies:true,evidence:`Jupiter aspects ${ninthLord}`}]:[]),...(["own-sign","exalted"].includes(dignity(ninthLord)?.dignity||"")?[{rule:"ninth-lord-dignity",applies:true,evidence:`${ninthLord} is ${dignity(ninthLord)?.dignity}`}]:[])],pitruEffective=Math.max(0,pitruEvidence.length-Math.min(1,pitruMitigations.length));
  const patterns=[
    {id:"mangal",label:"Mangal/Kuja structural pattern",detected:mangalHits>0,severity:severity(mangalEffective),rawSeverity:severity(mangalHits),evidence:mangalRefs,cancellationsOrMitigations:mangalMitigations,convention:"Mars in 1, 2, 4, 7, 8 or 12 from Lagna, Moon and Venus",sourceKey:DOSHA_RULEBOOK.sourceKeys[0]},
    {id:"kaal-sarpa",label:"Kaal Sarpa enclosure candidate",detected:allContained,severity:allContained?(kaalMitigations.length?"moderate":"high"):contained.length===6?"low":"none",rawSeverity:allContained?"high":contained.length===6?"low":"none",evidence:{containedPlanets:contained,totalClassicalPlanets:7,rahuHouse,type:KAAL_SARPA_TYPES[rahuHouse-1],nodeAxis:{rahu:{sign:rahu.sign,signName:SIGNS[rahu.sign]},ketu:{sign:ketu.sign,signName:SIGNS[ketu.sign]}}},cancellationsOrMitigations:kaalMitigations,convention:"All seven classical planets within one node-defined semicircle; boundary tolerance 0.0001°",sourceKey:DOSHA_RULEBOOK.sourceKeys[1]},
    {id:"kemadruma",label:"Kemadruma structural candidate",detected:kemadrumaPrimary,severity:kemadrumaEffective?"moderate":kemadrumaPrimary?"low":"none",rawSeverity:kemadrumaPrimary?"moderate":"none",evidence:{planetsInSecondOrTwelfthFromMoon:adjacent.map((item)=>({name:item.name,house:house(moon.sign,item.sign)}))},cancellationsOrMitigations:kemadrumaCancellations,convention:"No Mars, Mercury, Jupiter, Venus or Saturn in 2nd/12th from Moon; cancellation checks reported separately",sourceKey:DOSHA_RULEBOOK.sourceKeys[2]},
    {id:"pitru-candidate",label:"Pitru-related affliction candidate",detected:pitruEvidence.length>0,severity:severity(pitruEffective),rawSeverity:severity(pitruEvidence.length),evidence:{observations:pitruEvidence,ninthHouse:{sign:ninthSign,signName:SIGNS[ninthSign],lord:ninthLord,lordHouse:house(lagna.sign,ninthLordPlacement.sign)}},cancellationsOrMitigations:pitruMitigations,convention:"Conservative Sun/node/Saturn and 9th-house structural screen; not a lineage, health, or family verdict",sourceKey:DOSHA_RULEBOOK.sourceKeys[3]},
  ];
  return{schemaVersion:"sahadeva-doshas-1",subject:{name:chart.input.name,place:chart.input.place},patterns,summary:{detected:patterns.filter((item)=>item.detected).length,effectiveModerateOrHigh:patterns.filter((item)=>["moderate","high"].includes(item.severity)).length,notice:"Detection and effective severity are separate so cancellations and mitigations remain visible."},rulebook:DOSHA_RULEBOOK,safety:{status:"research-preview",notice:"These are traditional structural labels, not facts about morality, ancestors, health, fertility, lifespan, or inevitable events. Never use a single Dosha to reject a person or make a high-stakes decision."}};
}
