import type{GrahaName}from"./schema";
import { TIMING_TOPIC_CONFIG } from "./topicConfig";
export const JUDGMENT_TOPICS=["career","education","property","relationships","spirituality","wealth","health","children"]as const;
export type JudgmentTopic=(typeof JUDGMENT_TOPICS)[number];
export type JudgmentTopicConfig={title:string;house:number;secondaryHouses:number[];varga:string;karakas:GrahaName[];questions:string[];sourceKeys:string[]};
export const JUDGMENT_TOPIC_CONFIG:Record<JudgmentTopic,JudgmentTopicConfig>={
career:{title:"Career and public contribution",house:10,secondaryHouses:[2,6,11],varga:"D10",karakas:["Sun","Saturn","Mercury"],questions:["Which responsibilities currently require visible ownership?","Does the present choice favour stability, skill growth, or independence?","What practical evidence would show that the work direction is improving?"],sourceKeys:["judgment:career:house-lord","judgment:career:d10-confirmation","judgment:career:strength-and-timing","judgment:career:karakas-and-supporting-houses"]},
education:{title:"Education and learning",house:TIMING_TOPIC_CONFIG.education.house,secondaryHouses:[...TIMING_TOPIC_CONFIG.education.secondaryHouses],varga:"D24",karakas:[...TIMING_TOPIC_CONFIG.education.karakas],questions:["What is being learned?","Which learning method is sustainable?"],sourceKeys:["judgment:education:house-lord","judgment:education:d24-confirmation","judgment:education:karakas-and-supporting-houses","judgment:education:timing"]},
property:{title:"Home and property",house:4,secondaryHouses:[2,11,12],varga:"D4",karakas:["Mars","Venus"],questions:["Is the decision about use, ownership, location, or timing?"],sourceKeys:["judgment:property:house-lord","judgment:property:d4-confirmation","judgment:property:karakas-and-supporting-houses","judgment:property:timing"]},
relationships:{title:"Relationships and agreements",house:7,secondaryHouses:[2,8,11],varga:"D9",karakas:["Venus","Jupiter"],questions:["Which expectations or agreements need clarification?"],sourceKeys:["judgment:relationships:house-lord","judgment:relationships:d9-confirmation","judgment:relationships:karakas-and-supporting-houses","judgment:relationships:timing"]},
spirituality:{title:"Meaning and spiritual practice",house:9,secondaryHouses:[5,8,12],varga:"D20",karakas:["Jupiter","Ketu"],questions:["Which existing practice or tradition should guide this inquiry?"],sourceKeys:["judgment:spirituality:house-lord","judgment:spirituality:d20-confirmation","judgment:spirituality:karakas-and-supporting-houses","judgment:spirituality:timing"]},
wealth:{title:"Resources and financial structure",house:2,secondaryHouses:[5,9,11],varga:"D2",karakas:["Jupiter","Venus","Mercury"],questions:["Is the question about earning, saving, obligations, or risk?","What non-astrological financial evidence should guide the decision?"],sourceKeys:["judgment:wealth:house-lord","judgment:wealth:d2-confirmation","judgment:wealth:karakas-and-supporting-houses","judgment:wealth:timing"]},
health:{title:"Health routines and vitality",house:1,secondaryHouses:[6,8,12],varga:"D30",karakas:["Sun","Moon","Saturn"],questions:["Which daily routine (sleep, food, movement) is realistic to protect this month?","Is a professional check-up already overdue regardless of the chart?"],sourceKeys:["judgment:health:house-lord","judgment:health:d30-confirmation","judgment:health:karakas-and-supporting-houses","judgment:health:timing"]},
children:{title:"Children, mentoring and creativity",house:5,secondaryHouses:[9,11,2],varga:"D7",karakas:["Jupiter"],questions:["Is the question about timing, readiness, or the relationship itself?","What practical support is already available to the family?"],sourceKeys:["judgment:children:house-lord","judgment:children:d7-confirmation","judgment:children:karakas-and-supporting-houses","judgment:children:timing"]}}
