import { GEONAMES_LOCATIONS } from "./geonames.generated";

export type KnownLocation = {
  name: string;
  aliases?: string[];
  mandal?: string;
  district?: string;
  state: string;
  country: string;
  latitude: number;
  longitude: number;
  timezone: string;
  timezoneOffset: number;
  precision?: "locality-center" | "city-center";
};

// Curated coordinates are intentionally transparent and offline: selecting a
// place never sends the birth-place query to a third-party geocoder.
export const KNOWN_LOCATIONS: KnownLocation[] = [
  {
    name: "Ahmedabad",
    aliases: ["Amdavad"],
    district: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    latitude: 23.0225,
    longitude: 72.5714,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Surat",
    district: "Surat",
    state: "Gujarat",
    country: "India",
    latitude: 21.1702,
    longitude: 72.8311,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Vadodara",
    aliases: ["Baroda"],
    district: "Vadodara",
    state: "Gujarat",
    country: "India",
    latitude: 22.3072,
    longitude: 73.1812,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Rajkot",
    district: "Rajkot",
    state: "Gujarat",
    country: "India",
    latitude: 22.3039,
    longitude: 70.8022,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Gandhinagar",
    district: "Gandhinagar",
    state: "Gujarat",
    country: "India",
    latitude: 23.2156,
    longitude: 72.6369,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Bhavnagar",
    district: "Bhavnagar",
    state: "Gujarat",
    country: "India",
    latitude: 21.7645,
    longitude: 72.1519,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Jamnagar",
    district: "Jamnagar",
    state: "Gujarat",
    country: "India",
    latitude: 22.4707,
    longitude: 70.0577,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Hyderabad",
    district: "Hyderabad",
    state: "Telangana",
    country: "India",
    latitude: 17.385,
    longitude: 78.4867,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Secunderabad",
    district: "Hyderabad",
    state: "Telangana",
    country: "India",
    latitude: 17.4399,
    longitude: 78.4983,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Warangal",
    district: "Hanamkonda",
    state: "Telangana",
    country: "India",
    latitude: 17.9689,
    longitude: 79.5941,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Nizamabad",
    district: "Nizamabad",
    state: "Telangana",
    country: "India",
    latitude: 18.6725,
    longitude: 78.0941,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Karimnagar",
    district: "Karimnagar",
    state: "Telangana",
    country: "India",
    latitude: 18.4386,
    longitude: 79.1288,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Khammam",
    district: "Khammam",
    state: "Telangana",
    country: "India",
    latitude: 17.2473,
    longitude: 80.1514,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Nalgonda",
    district: "Nalgonda",
    state: "Telangana",
    country: "India",
    latitude: 17.0575,
    longitude: 79.2684,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Mahbubnagar",
    district: "Mahbubnagar",
    state: "Telangana",
    country: "India",
    latitude: 16.7488,
    longitude: 77.9854,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Adilabad",
    district: "Adilabad",
    state: "Telangana",
    country: "India",
    latitude: 19.6641,
    longitude: 78.532,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Siddipet",
    district: "Siddipet",
    state: "Telangana",
    country: "India",
    latitude: 18.1018,
    longitude: 78.852,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Suryapet",
    district: "Suryapet",
    state: "Telangana",
    country: "India",
    latitude: 17.1405,
    longitude: 79.62,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Vijayawada",
    district: "NTR",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.5062,
    longitude: 80.648,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Visakhapatnam",
    district: "Visakhapatnam",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 17.6868,
    longitude: 83.2185,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Guntur",
    district: "Guntur",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.3067,
    longitude: 80.4365,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Tirupati",
    district: "Tirupati",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 13.6288,
    longitude: 79.4192,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Nellore",
    district: "SPSR Nellore",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 14.4426,
    longitude: 79.9865,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Kurnool",
    district: "Kurnool",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 15.8281,
    longitude: 78.0373,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Kakinada",
    district: "Kakinada",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.9891,
    longitude: 82.2475,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Rajamahendravaram",
    district: "East Godavari",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 17.0005,
    longitude: 81.804,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Kadapa",
    district: "YSR Kadapa",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 14.4673,
    longitude: 78.8242,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Anantapur",
    district: "Anantapur",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 14.6819,
    longitude: 77.6006,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Ongole",
    district: "Prakasam",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 15.5057,
    longitude: 80.0499,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Eluru",
    district: "Eluru",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.7107,
    longitude: 81.0952,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Machilipatnam",
    district: "Krishna",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.1875,
    longitude: 81.1389,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Srikakulam",
    district: "Srikakulam",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 18.2969,
    longitude: 83.8968,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Vizianagaram",
    aliases: ["Vijayanagaram", "Vijaya Nagaram"],
    district: "Vizianagaram",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 18.1067,
    longitude: 83.3956,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Amaravati",
    district: "Guntur",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.573,
    longitude: 80.358,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Bhadrachalam",
    mandal: "Bhadrachalam",
    district: "Bhadradri Kothagudem",
    state: "Telangana",
    country: "India",
    latitude: 17.6688,
    longitude: 80.8936,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
    precision: "locality-center",
  },
  {
    name: "Kothagudem",
    aliases: ["Palvancha Kothagudem"],
    mandal: "Kothagudem",
    district: "Bhadradri Kothagudem",
    state: "Telangana",
    country: "India",
    latitude: 17.556,
    longitude: 80.6178,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Asifabad",
    aliases: ["Komaram Bheem"],
    mandal: "Asifabad",
    district: "Kumuram Bheem Asifabad",
    state: "Telangana",
    country: "India",
    latitude: 19.365,
    longitude: 79.274,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Jagtial",
    mandal: "Jagtial",
    district: "Jagtial",
    state: "Telangana",
    country: "India",
    latitude: 18.7931,
    longitude: 78.916,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Jangaon",
    mandal: "Jangaon",
    district: "Jangaon",
    state: "Telangana",
    country: "India",
    latitude: 17.726,
    longitude: 79.1524,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Bhupalpally",
    aliases: ["Jayashankar"],
    mandal: "Bhupalpally",
    district: "Jayashankar Bhupalpally",
    state: "Telangana",
    country: "India",
    latitude: 18.4294,
    longitude: 79.8635,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Kamareddy",
    mandal: "Kamareddy",
    district: "Kamareddy",
    state: "Telangana",
    country: "India",
    latitude: 18.3205,
    longitude: 78.337,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Bhainsa",
    mandal: "Bhainsa",
    district: "Nirmal",
    state: "Telangana",
    country: "India",
    latitude: 19.1002,
    longitude: 77.9634,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Mancherial",
    mandal: "Mancherial",
    district: "Mancherial",
    state: "Telangana",
    country: "India",
    latitude: 18.8714,
    longitude: 79.4443,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Medak",
    mandal: "Medak",
    district: "Medak",
    state: "Telangana",
    country: "India",
    latitude: 18.0529,
    longitude: 78.2619,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Shamirpet",
    mandal: "Shamirpet",
    district: "Medchal-Malkajgiri",
    state: "Telangana",
    country: "India",
    latitude: 17.5941,
    longitude: 78.5745,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
    precision: "locality-center",
  },
  {
    name: "Mulugu",
    mandal: "Mulugu",
    district: "Mulugu",
    state: "Telangana",
    country: "India",
    latitude: 18.191,
    longitude: 79.943,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Nagarkurnool",
    mandal: "Nagarkurnool",
    district: "Nagarkurnool",
    state: "Telangana",
    country: "India",
    latitude: 16.4821,
    longitude: 78.3247,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Narayanpet",
    mandal: "Narayanpet",
    district: "Narayanpet",
    state: "Telangana",
    country: "India",
    latitude: 16.7449,
    longitude: 77.496,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Peddapalli",
    mandal: "Peddapalli",
    district: "Peddapalli",
    state: "Telangana",
    country: "India",
    latitude: 18.6151,
    longitude: 79.3741,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Sangareddy",
    aliases: ["Sangareddipet"],
    mandal: "Sangareddy",
    district: "Sangareddy",
    state: "Telangana",
    country: "India",
    latitude: 17.6248,
    longitude: 78.0867,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Vikarabad",
    mandal: "Vikarabad",
    district: "Vikarabad",
    state: "Telangana",
    country: "India",
    latitude: 17.3381,
    longitude: 77.9044,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Wanaparthy",
    mandal: "Wanaparthy",
    district: "Wanaparthy",
    state: "Telangana",
    country: "India",
    latitude: 16.3623,
    longitude: 78.0622,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Yadadri",
    aliases: ["Yadagirigutta"],
    mandal: "Yadagirigutta",
    district: "Yadadri Bhuvanagiri",
    state: "Telangana",
    country: "India",
    latitude: 17.5897,
    longitude: 78.9443,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
    precision: "locality-center",
  },
  {
    name: "Basara",
    aliases: ["Basar"],
    mandal: "Mudhole",
    district: "Nirmal",
    state: "Telangana",
    country: "India",
    latitude: 18.8817,
    longitude: 77.953,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
    precision: "locality-center",
  },
  {
    name: "Araku Valley",
    aliases: ["Araku"],
    mandal: "Araku Valley",
    district: "Alluri Sitharama Raju",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 18.3273,
    longitude: 82.8775,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
    precision: "locality-center",
  },
  {
    name: "Paderu",
    mandal: "Paderu",
    district: "Alluri Sitharama Raju",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 18.0778,
    longitude: 82.6676,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Rayachoti",
    mandal: "Rayachoti",
    district: "Annamayya",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 14.0583,
    longitude: 78.751,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Bapatla",
    mandal: "Bapatla",
    district: "Bapatla",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 15.9042,
    longitude: 80.4676,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Chittoor",
    mandal: "Chittoor",
    district: "Chittoor",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 13.2172,
    longitude: 79.1003,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Amalapuram",
    mandal: "Amalapuram",
    district: "Dr. B. R. Ambedkar Konaseema",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.5787,
    longitude: 82.0061,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Ambajipeta",
    mandal: "Ambajipeta",
    district: "Dr. B. R. Ambedkar Konaseema",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.5908,
    longitude: 81.9238,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
    precision: "locality-center",
  },
  {
    name: "Ravulapalem",
    mandal: "Ravulapalem",
    district: "Dr. B. R. Ambedkar Konaseema",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.7607,
    longitude: 81.833,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
    precision: "locality-center",
  },
  {
    name: "Rajahmundry",
    aliases: ["Rajamahendravaram"],
    district: "East Godavari",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 17.0005,
    longitude: 81.804,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Puttaparthi",
    mandal: "Puttaparthi",
    district: "Sri Sathya Sai",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 14.1652,
    longitude: 77.8117,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Narasaraopet",
    mandal: "Narasaraopet",
    district: "Palnadu",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.2354,
    longitude: 80.0477,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Parvathipuram",
    mandal: "Parvathipuram",
    district: "Parvathipuram Manyam",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 18.783,
    longitude: 83.425,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Nandyal",
    mandal: "Nandyal",
    district: "Nandyal",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 15.4777,
    longitude: 78.4836,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Bhimavaram",
    mandal: "Bhimavaram",
    district: "West Godavari",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.5449,
    longitude: 81.5212,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Narasapuram",
    aliases: ["Narsapur"],
    mandal: "Narasapuram",
    district: "West Godavari",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.4344,
    longitude: 81.6985,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Gudivada",
    mandal: "Gudivada",
    district: "Krishna",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.4355,
    longitude: 80.9957,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Tenali",
    mandal: "Tenali",
    district: "Guntur",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.2395,
    longitude: 80.6493,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Proddatur",
    mandal: "Proddatur",
    district: "YSR Kadapa",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 14.7502,
    longitude: 78.5481,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Hindupur",
    mandal: "Hindupur",
    district: "Sri Sathya Sai",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 13.8281,
    longitude: 77.4914,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Srisailam",
    mandal: "Srisailam",
    district: "Nandyal",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 16.0728,
    longitude: 78.8687,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
    precision: "locality-center",
  },
  {
    name: "Lepakshi",
    mandal: "Lepakshi",
    district: "Sri Sathya Sai",
    state: "Andhra Pradesh",
    country: "India",
    latitude: 13.8039,
    longitude: 77.609,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
    precision: "locality-center",
  },
  {
    name: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0827,
    longitude: 80.2707,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Bengaluru",
    state: "Karnataka",
    country: "India",
    latitude: 12.9716,
    longitude: 77.5946,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Mumbai",
    state: "Maharashtra",
    country: "India",
    latitude: 19.076,
    longitude: 72.8777,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "New Delhi",
    state: "Delhi",
    country: "India",
    latitude: 28.6139,
    longitude: 77.209,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "Pune",
    state: "Maharashtra",
    country: "India",
    latitude: 18.5204,
    longitude: 73.8567,
    timezone: "Asia/Kolkata",
    timezoneOffset: 5.5,
  },
  {
    name: "London",
    state: "England",
    country: "United Kingdom",
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: "Europe/London",
    timezoneOffset: 0,
  },
  {
    name: "New York",
    aliases: ["New York City", "NYC"],
    state: "New York",
    country: "United States",
    latitude: 40.7128,
    longitude: -74.006,
    timezone: "America/New_York",
    timezoneOffset: -5,
  },
  {
    name: "San Francisco",
    state: "California",
    country: "United States",
    latitude: 37.7749,
    longitude: -122.4194,
    timezone: "America/Los_Angeles",
    timezoneOffset: -8,
  },
  {
    name: "Toronto",
    state: "Ontario",
    country: "Canada",
    latitude: 43.6532,
    longitude: -79.3832,
    timezone: "America/Toronto",
    timezoneOffset: -5,
  },
  {
    name: "Sydney",
    state: "New South Wales",
    country: "Australia",
    latitude: -33.8688,
    longitude: 151.2093,
    timezone: "Australia/Sydney",
    timezoneOffset: 10,
  },
  {
    name: "Singapore",
    state: "Singapore",
    country: "Singapore",
    latitude: 1.3521,
    longitude: 103.8198,
    timezone: "Asia/Singapore",
    timezoneOffset: 8,
  },
  {
    name: "Dubai",
    state: "Dubai",
    country: "United Arab Emirates",
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: "Asia/Dubai",
    timezoneOffset: 4,
  },
  {
    name: "Tokyo",
    state: "Tokyo",
    country: "Japan",
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: "Asia/Tokyo",
    timezoneOffset: 9,
  },
  {
    name: "Berlin",
    state: "Berlin",
    country: "Germany",
    latitude: 52.52,
    longitude: 13.405,
    timezone: "Europe/Berlin",
    timezoneOffset: 1,
  },
  {
    name: "Johannesburg",
    state: "Gauteng",
    country: "South Africa",
    latitude: -26.2041,
    longitude: 28.0473,
    timezone: "Africa/Johannesburg",
    timezoneOffset: 2,
  },
  {
    name: "Auckland",
    state: "Auckland",
    country: "New Zealand",
    latitude: -36.8509,
    longitude: 174.7645,
    timezone: "Pacific/Auckland",
    timezoneOffset: 12,
  },
  {
    name: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    latitude: 27.7172,
    longitude: 85.324,
    timezone: "Asia/Kathmandu",
    timezoneOffset: 5.75,
  },
  ...GEONAMES_LOCATIONS,
];

export const locationLabel = (location: KnownLocation) =>
  `${location.name}, ${location.district && location.district !== location.name ? `${location.district}, ` : ""}${location.state}, ${location.country}`;
const normalize = (value: string) =>
  value
    .normalize("NFKD")
    .replace(/\p{Diacritic}/gu, "")
    .toLocaleLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
export type LocationResolution =
  | { status: "none"; matches: KnownLocation[] }
  | { status: "resolved"; location: KnownLocation; matches: [KnownLocation] }
  | { status: "ambiguous"; matches: KnownLocation[] };
const uniqueLocations = (locations: KnownLocation[]) =>
  locations.filter(
    (location, index) =>
      locations.findIndex(
        (candidate) =>
          candidate.latitude === location.latitude &&
          candidate.longitude === location.longitude &&
          candidate.timezone === location.timezone,
      ) === index,
  );
const words = (value: string) => normalize(value).split(" ").filter(Boolean);
const editDistance = (left: string, right: string) => {
  const row = Array.from({ length: right.length + 1 }, (_, index) => index);
  for (let i = 1; i <= left.length; i++) {
    let diagonal = row[0];
    row[0] = i;
    for (let j = 1; j <= right.length; j++) {
      const previous = row[j];
      row[j] = Math.min(
        row[j] + 1,
        row[j - 1] + 1,
        diagonal + (left[i - 1] === right[j - 1] ? 0 : 1),
      );
      diagonal = previous;
    }
  }
  return row[right.length];
};
const locationNames = (location: KnownLocation) =>
  [location.name, ...(location.aliases || [])].map(normalize);
const locationHaystack = (location: KnownLocation) =>
  normalize(
    [
      location.name,
      ...(location.aliases || []),
      location.mandal || "",
      location.district || "",
      location.state,
      location.country,
    ].join(" "),
  );
function rankedLocationMatches(query: string, catalogue: KnownLocation[]) {
  const needle = normalize(query),
    queryWords = words(query),
    firstPart = normalize(query.split(",")[0] || query),
    administrativeWords = new Set([
      "district",
      "mandal",
      "county",
      "state",
      "province",
    ]);
  return catalogue
    .map((location) => {
      const names = locationNames(location),
        haystack = locationHaystack(location),
        haystackWords = new Set(words(haystack));
      const exactName =
        names.includes(firstPart) || names.some((name) => needle === name);
      const containedName = names.some(
        (name) =>
          needle === name ||
          needle.startsWith(`${name} `) ||
          needle.includes(` ${name} `),
      );
      const fuzzyName = Math.min(
        ...names.map((name) => editDistance(firstPart, name)),
      );
      const relevant = queryWords.filter(
        (word) => !administrativeWords.has(word),
      );
      const overlap = relevant.filter((word) => haystackWords.has(word)).length;
      const score =
        (exactName
          ? 100
          : containedName
            ? 85
            : fuzzyName <= Math.max(1, Math.floor(firstPart.length / 6))
              ? 65
              : 0) +
        overlap * 3 -
        fuzzyName;
      return { location, score, exactName, containedName, fuzzyName, overlap };
    })
    .filter((item) => item.score >= 60)
    .sort(
      (a, b) =>
        b.score - a.score ||
        a.fuzzyName - b.fuzzyName ||
        a.location.name.localeCompare(b.location.name),
    );
}
export function resolveKnownLocation(
  query: string,
  catalogue: KnownLocation[] = KNOWN_LOCATIONS,
): LocationResolution {
  const needle = normalize(query);
  if (!needle) return { status: "none", matches: [] };
  const exact = catalogue.filter((location) =>
    [
      location.name,
      ...(location.aliases || []),
      location.mandal || "",
      location.district || "",
      locationLabel(location),
    ].some((value) => normalize(value) === needle),
  );
  const ranked = rankedLocationMatches(query, catalogue),
    best = ranked[0]?.score;
  const matches = exact.length
    ? exact
    : ranked.filter((item) => item.score === best).map((item) => item.location);
  if (!matches.length)
    return {
      status: "none",
      matches: ranked.slice(0, 5).map((item) => item.location),
    };
  const distinct = uniqueLocations(matches);
  return distinct.length === 1
    ? { status: "resolved", location: distinct[0], matches: [distinct[0]] }
    : { status: "ambiguous", matches: distinct };
}
export function findKnownLocation(query: string) {
  const result = resolveKnownLocation(query);
  return result.status === "resolved" ? result.location : null;
}
export function searchKnownLocations(query: string, limit = 20) {
  const needle = normalize(query);
  if (!needle) return KNOWN_LOCATIONS.slice(0, limit);
  const direct = KNOWN_LOCATIONS.filter((location) =>
    locationHaystack(location).includes(needle),
  );
  const ranked = rankedLocationMatches(query, KNOWN_LOCATIONS).map(
    (item) => item.location,
  );
  // Ranking puts exact names and aliases first. Catalogue-order substring
  // matches fill the remainder for broad administrative searches.
  return uniqueLocations([...ranked, ...direct]).slice(0, limit);
}
