import { NAKSHATRAS, SIGNS } from "./constants";
import { calculateAspects } from "./advanced";
import type { ChartResult, Placement } from "./schema";

export type AyanamsaId="lahiri"|"krishnamurti"|"raman"|"fagan-bradley";
const OFFSETS_FROM_LAHIRI:Record<AyanamsaId,number>={lahiri:0,krishnamurti:-5.6/60,raman:-(1+27/60+11/3600),"fagan-bradley":52.433/60};
const META:Record<AyanamsaId,{name:string;validation:string;swissMode:number}>={lahiri:{name:"Lahiri",validation:"validated-in-engine",swissMode:1},krishnamurti:{name:"Krishnamurti",validation:"comparison-offset-unvalidated",swissMode:5},raman:{name:"Raman",validation:"comparison-offset-unvalidated",swissMode:3},"fagan-bradley":{name:"Fagan/Bradley",validation:"comparison-offset-unvalidated",swissMode:0}};
export const SPECIAL_ASPECT_MATRIX={Sun:[7],Moon:[7],Mars:[4,7,8],Mercury:[7],Jupiter:[5,7,9],Venus:[7],Saturn:[3,7,10],Rahu:[7],Ketu:[7]} as const;
const norm=(value:number)=>((value%360)+360)%360;

export function projectAyanamsa(chart:ChartResult,id:AyanamsaId){
  const ayanamsaDegrees=chart.engine.ayanamsaDegrees+OFFSETS_FROM_LAHIRI[id],placements=chart.placements.map((item)=>{const longitude=norm(item.tropicalLongitude!-ayanamsaDegrees),sign=Math.floor(longitude/30),nakshatraIndex=Math.floor(longitude/(360/27));return{...item,longitude,sign,signName:SIGNS[sign],degree:longitude%30,nakshatra:NAKSHATRAS[nakshatraIndex],pada:Math.floor((longitude%(360/27))/(360/108))+1};}) as Placement[];
  const lagna=placements.find((item)=>item.name==="Lagna")!;return{schemaVersion:"sahadeva-ayanamsa-projection-1",selected:{id,name:META[id].name,ayanamsaDegrees,offsetFromLahiriDegrees:OFFSETS_FROM_LAHIRI[id],validation:META[id].validation,swissEphemerisModeReference:META[id].swissMode},placements:placements.map((item)=>({...item,houseFromLagna:((item.sign-lagna.sign+12)%12)+1})),aspects:{matrix:SPECIAL_ASPECT_MATRIX,detected:calculateAspects(placements),validation:{mars:SPECIAL_ASPECT_MATRIX.Mars.join(",")==="4,7,8",jupiter:SPECIAL_ASPECT_MATRIX.Jupiter.join(",")==="5,7,9",saturn:SPECIAL_ASPECT_MATRIX.Saturn.join(",")==="3,7,10"}},boundaryChangesFromLahiri:placements.filter((item)=>item.sign!==chart.placements.find((original)=>original.name===item.name)!.sign||item.nakshatra!==chart.placements.find((original)=>original.name===item.name)!.nakshatra).map((item)=>{const original=chart.placements.find((row)=>row.name===item.name)!;return{name:item.name,lahiri:{sign:original.sign,signName:original.signName,nakshatra:original.nakshatra,pada:original.pada},selected:{sign:item.sign,signName:item.signName,nakshatra:item.nakshatra,pada:item.pada}};}),scope:{fullDerivedChartRecomputed:false,notice:id==="lahiri"?"Lahiri uses the engine's validated ayanamsa.":"Placements and sign-based aspects are reprojected. Vargas, dashas, strengths, Panchanga, houses and reports remain Lahiri until this convention is independently validated and integrated end-to-end."},source:{name:"Swiss Ephemeris 2.10 sidereal-mode identifiers",url:"https://www.astro.com/ftp/swisseph/doc/swephprg.2.10.pdf"},safety:{status:"research-preview",notice:"Ayanamsa selection is a calculation convention; comparison does not establish that one tradition is objectively correct."}};
}
