import type { JudgmentTier, RuleProvenance } from "./consultation";
import type { PrashnaTradition } from "./prashnaRulebook";

export type PrashnaRuleMaturity = "structural" | "located" | "reproduced" | "reviewed" | "calibrated";

export type PrashnaRuleDefinition = {
  family: string;
  tradition: Exclude<PrashnaTradition, "integrated"> | "shared";
  sourceIds: string[];
  locators: string[];
  statement: string;
  requiredInputs: string[];
  effect: "support" | "oppose" | "qualify" | "classify";
  exceptions: string[];
  maturity: PrashnaRuleMaturity;
  testObligations: string[];
};

export const PRASHNA_RULES: readonly PrashnaRuleDefinition[] = [
  { family: "prashna:derived-house", tradition: "shared", sourceIds: ["book-daivajna-vallabha"], locators: ["Chapter II, verses 18–19"], statement: "Treat the house representing the subject as a derived ascendant.", requiredInputs: ["reference house", "topic house"], effect: "classify", exceptions: ["Use the radical ascendant when the question concerns the querent directly."], maturity: "located", testObligations: ["reference-house rotation", "house wraparound"] },
  { family: "prashna:classical-dhatu-moola-jeeva", tradition: "classical", sourceIds: ["book-chappanna-prasana-sastra"], locators: ["Navamsa Dhatu–Moola–Jeeva passage; scan verification pending"], statement: "Classify the subject from the ascendant Navamsa sequence.", requiredInputs: ["ascendant sign", "ascendant degree"], effect: "classify", exceptions: ["Do not infer a verdict from classification alone."], maturity: "structural", testObligations: ["odd signs", "even signs", "all nine Navamsas", "boundary degrees"] },
  { family: "prashna:classical-silent-query-verses-12-13", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter X, verses 12–13"], statement: "Aries/Leo/Scorpio with Sun or Mars influence supports Dhatu; Gemini/Virgo/Capricorn/Aquarius with Saturn or Mercury influence supports Moola; Taurus/Cancer/Libra/Sagittarius/Pisces with Moon, Venus or Jupiter influence supports Jeeva. Influences from different families are retained as a mixture.", requiredInputs: ["ascendant sign", "planet conjunctions to ascendant", "classical graha drishti to ascendant"], effect: "classify", exceptions: ["This is independent from the Chappanna Navamsa sequence. The final mixed-family clause does not state precedence, so all families remain visible and the rule is non-scoring."], maturity: "located", testObligations: ["every sign family", "each planet family", "conjunction", "graha drishti", "wrong-sign influence", "no influence", "mixed families", "separate Chappanna evidence", "zero score"] },
  { family: "prashna:classical-silent-query-verses-6-8", tradition: "classical", sourceIds: ["book-daivajna-vallabha", "book-prasna-marga-raman"], locators: ["Daivajna Vallabha, Chapter X, verses 6–8, read with verse 4's local strength instruction", "Prasna Marga Part II, Chapter XXI, stanzas 19–20, notes and friendship table"], statement: "The rising sign classifies an object's length as long, medium or short; the unique highest planet under the chapter's own/friendly/neutral/inimical Navamsa hierarchy supplies one source color and shape pair.", requiredInputs: ["ascendant sign", "seven planet color/shape table", "D9 sign and lord for every classical planet", "natural friendship table"], effect: "classify", exceptions: ["Own, friendly, neutral and inimical Navamsas rank in that order. If any D9 input is unavailable or the highest tier is tied, selection abstains; generic Shadbala is never used as an unstated tie-break."], maturity: "reproduced", testObligations: ["all twelve sign lengths", "all seven color mappings", "all seven shape mappings", "every relationship tier", "unique highest tier", "highest-tier tie", "missing D9", "invalid sign", "no Shadbala tie-break", "one neutral observation", "dual-source provenance"] },
  { family: "prashna:classical-silent-query-verses-3-4", tradition: "classical", sourceIds: ["book-daivajna-vallabha", "book-prasna-marga-raman"], locators: ["Daivajna Vallabha, Chapter X, verses 3–4", "Prasna Marga Part II, Chapter XXI, stanzas 19–20, notes and friendship table"], statement: "The D1 house occupied by the unique highest planet under the local Navamsa relationship hierarchy classifies the silent query's stated subject.", requiredInputs: ["seven-planet D9 relationship ranking", "unique strongest planet", "selected planet D1 house"], effect: "classify", exceptions: ["A strength tie or missing D9 input causes abstention. The translation supplies six roles for five houses in verse 3; sister and enemy are both retained for house 6. Houses 2, 8, 11 and 12 have no stated mapping. This is symbolic classification, not a fact about a third party."], maturity: "reproduced", testObligations: ["houses 1, 3, 4, 5, 6, 7, 9 and 10", "house-6 dual candidates", "unmapped houses", "strength tie", "missing D9", "one neutral observation", "dual-source provenance"] },
  { family: "prashna:classical-rising-mode", tradition: "classical", sourceIds: ["book-daivajna-vallabha", "book-prasna-marga-raman"], locators: ["Daivajna Vallabha, Chapter II, verses 20–21", "Prasna Marga Part I, rising-sign classification"], statement: "Head-rising signs support general accomplishment; contrary rising conditions oppose it; mixed conditions remain mixed.", requiredInputs: ["ascendant sign"], effect: "qualify", exceptions: ["Topic-specific rules can override this general testimony."], maturity: "located", testObligations: ["six head-rising signs", "five back-rising signs", "Pisces both-rising"] },
  { family: "prashna:classical-upachaya-marriage", tradition: "classical", sourceIds: ["book-prasna-marga-raman"], locators: ["Prasna Marga Part II, Chapter XVII, stanza 27"], statement: "Venus and the lord of the seventh both occupying Upachaya houses support happiness after marriage and children.", requiredInputs: ["ascendant sign", "Venus sign", "seventh-lord sign"], effect: "support", exceptions: ["This is one supporting combination, not an independent guarantee of marriage, timing, fertility or marital quality."], maturity: "located", testObligations: ["both in Upachayas", "Venus outside Upachayas", "seventh lord outside Upachayas", "Venus also seventh lord"] },
  { family: "prashna:classical-upachaya-children", tradition: "classical", sourceIds: ["book-prasna-marga-raman"], locators: ["Prasna Marga Part II, Chapter XVII, note immediately following stanza 27"], statement: "Raman extends the karaka-and-lord Upachaya principle: Jupiter and the fifth lord in Upachayas support prosperity after a child's birth.", requiredInputs: ["ascendant sign", "Jupiter sign", "fifth-lord sign"], effect: "support", exceptions: ["This commentary extension describes prosperity after birth and must not be converted into a promise of conception, birth or timing."], maturity: "located", testObligations: ["both in Upachayas", "Jupiter outside Upachayas", "fifth lord outside Upachayas", "Jupiter also fifth lord"] },
  { family: "prashna:classical-children-stanza-18", tradition: "classical", sourceIds: ["book-prasna-marga-raman"], locators: ["Prasna Marga Part II, Chapter XVIII, stanza 18"], statement: "Birth of children is supported when Mars occupies the fifth, the fifth is Aries, Leo, Scorpio or Pisces, and Jupiter aspects it.", requiredInputs: ["ascendant sign", "Mars sign", "Jupiter sign", "Jupiter graha drishti"], effect: "support", exceptions: ["The translator explicitly renders putravaptim as children generally; this testimony is not event timing or a medical fertility claim."], maturity: "located", testObligations: ["each allowed fifth sign", "disallowed fifth sign", "Mars outside fifth", "Jupiter aspect present", "Jupiter aspect absent"] },
  { family: "prashna:classical-children-stanza-22", tradition: "classical", sourceIds: ["book-prasna-marga-raman"], locators: ["Prasna Marga Part II, Chapter XVIII, stanza 22 and following note"], statement: "Birth of children is supported when strong Jupiter occupies the ascendant, fifth or seventh and receives no natural-malefic aspect.", requiredInputs: ["ascendant sign", "Jupiter sign and house", "Jupiter strength", "natural-malefic graha drishti"], effect: "support", exceptions: ["The source note defines strength here through Pisces, Sagittarius, Cancer, or directional strength in the ascendant; conditional Moon and Mercury nature must be evaluated."], maturity: "located", testObligations: ["own-sign Jupiter", "exalted Jupiter", "ascendant directional strength", "wrong house", "fixed-malefic aspect", "waning-Moon aspect", "afflicted-Mercury aspect"] },
  { family: "prashna:classical-lost-property-verse-10", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Lost Property chapter, verse 10"], statement: "Recovery of lost property is supported when Venus occupies the second, Jupiter the twelfth, and a natural benefic occupies the ascendant.", requiredInputs: ["ascendant sign", "Venus house", "Jupiter house", "ascendant occupants", "conditional natural nature"], effect: "support", exceptions: ["This is one traditional testimony and must not be phrased as guaranteed recovery; Moon phase and Mercury association determine their natural nature."], maturity: "located", testObligations: ["all three clauses present", "Venus wrong house", "Jupiter wrong house", "no ascendant benefic", "waxing Moon benefic", "waning Moon exclusion", "afflicted Mercury exclusion"] },
  { family: "prashna:classical-lost-property-verses-1-3-location", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IX, verses 1–3"], statement: "Fixed D1, fixed D9 or Vargottama ascendant supplies same-place testimony; movable D1 or D9 supplies elsewhere testimony; dual D1 supplies outside-house testimony. All candidates and contradictions remain visible in one neutral observation.", requiredInputs: ["ascendant D1 sign", "ascendant D9 sign", "sign modality", "Vargottama comparison"], effect: "classify", exceptions: ["The verses' known-person, outsider, neighbour, thief-sex and form clauses are excluded and cannot be used to identify or accuse anyone. Repeated same-place/elsewhere clauses are evidence details, not independent votes."], maturity: "located", testObligations: ["all four movable signs", "all four fixed signs", "all four dual signs", "D9 movable and fixed", "Vargottama", "D1/D9 conflict", "one neutral observation", "no identity output"] },
  { family: "prashna:classical-lost-property-verse-14", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Lost Property chapter, verse 14"], statement: "Recovery is supported by full Moon, Jupiter, Venus or eligible Mercury in the ascendant, or by a natural benefic in the seventh.", requiredInputs: ["ascendant and seventh occupants", "full-Moon tithi", "conditional Mercury and Moon nature"], effect: "support", exceptions: ["Alternative clauses occurring together form one aggregated observation and one weight; they must not be double-counted as independent evidence."], maturity: "located", testObligations: ["full Moon ascendant", "non-full Moon exclusion", "Jupiter ascendant", "Venus ascendant", "unafflicted Mercury ascendant", "afflicted Mercury exclusion", "benefic seventh", "multiple alternatives deduplicated"] },
  { family: "prashna:classical-lost-property-verse-8", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IX, Lost Articles, verse 8"], statement: "The rising decanate classifies the loss as theft in the first, a fall in the second, or forgetting where the article was kept in the third; the third also indicates that it remains within the house.", requiredInputs: ["ascendant degree within sign"], effect: "classify", exceptions: ["This symbolic classification is not factual proof of theft and must never identify or accuse a person."], maturity: "reproduced", testObligations: ["0-degree boundary", "10-degree boundary", "20-degree boundary", "30-degree exclusion", "neutral non-culpability output"] },
  { family: "prashna:classical-lost-property-location-verse-9", tradition: "classical", sourceIds: ["book-daivajna-vallabha", "book-chappanna-prasana-sastra"], locators: ["Daivajna Vallabha, Chapter IX, Lost Articles, verse 9", "Chappanna or Prasana Sastra, stanza 41, Direction Taken by the Stolen Articles and note (printed page 51)"], statement: "Lost-property direction comes from an angular planet, selecting the strongest when several occupy angles, or from the rising sign when no planet is angular. Planet and sign direction tables are fixed by the sources; the rising Navamsa supplies distance evidence.", requiredInputs: ["ascendant longitude", "whole-sign angular houses", "planet direction table", "sign direction table", "planetary Shadbala when multiple angular planets", "rising Navamsa ordinal"], effect: "classify", exceptions: ["Ketu has no direction in the source table. Multiple angular planets require a unique completed strength maximum. Default whole-sign charts cannot compare planet Shadbala to Lagna/Bhava Bala. The scans leave current-ordinal versus completed-Navamsa Yojanas ambiguous, so both are exposed and no single distance is selected."], maturity: "reproduced", testObligations: ["all eight planet directions", "all twelve sign directions", "single angular planet", "no-angular fallback", "multiple unique strongest", "missing strength", "strength tie", "Ketu-only angle", "all nine Navamsa boundaries", "fifth-Navamsa marker", "distance abstention"] },
  { family: "prashna:classical-lost-property-benefic-recovery-cluster", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IX, verses 11–15"], statement: "The explicit full-Moon-in-ascendant clause of verse 11 and the overlapping benefic-house recovery clauses of verses 12, 13 and 15 provide one correlated recovery testimony when any implemented clause is satisfied.", requiredInputs: ["natural benefic classification", "planet houses", "full-Moon tithi", "Jupiter/Venus aspects to ascendant"], effect: "support", exceptions: ["Verse 11's undefined ‘very strong benefic’ threshold and grammatically ambiguous Sirshodaya alternative remain inactive. All matching clauses and verse numbers are exposed but contribute only one observation and one score weight; conditional Moon and Mercury nature is retained."], maturity: "located", testObligations: ["verse 11 full-Moon ascendant and phase boundary", "verse 12 house set", "verse 13 full-Moon aspect clause", "verse 13 quadrant-plus-Upachaya clause", "verse 13 second-plus-Upachaya clause", "verse 15 houses relative to Lagna and fourth", "no clause", "multi-verse deduplication"] },
  { family: "prashna:classical-lost-property-verse-16", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IX, verse 16"], statement: "A malefic-owned ascendant receiving a natural-malefic aspect opposes recovery; a natural benefic in the ascendant receiving another benefic's aspect supports recovery.", requiredInputs: ["ascendant sign lord", "conditional natural nature", "graha drishti", "ascendant occupants"], effect: "qualify", exceptions: ["When both clauses occur, preserve a neutral mixed observation with zero net weight rather than issuing two votes."], maturity: "located", testObligations: ["malefic sign lord plus malefic aspect", "malefic sign lord without aspect", "benefic occupant plus distinct benefic aspect", "single benefic only", "simultaneous opposing clauses"] },
  { family: "prashna:classical-lost-property-verse-17", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IX, verse 17"], statement: "Recovery is opposed when the seventh is Leo, Scorpio or Aquarius in its own Navamsa and receives natural-malefic aspect, or when Mars occupies the eighth in one of those named Navamsas.", requiredInputs: ["ascendant degree", "seventh sign and Navamsa", "natural-malefic graha drishti", "Mars house and D9 sign"], effect: "oppose", exceptions: ["The translation's ‘these Navamsas’ is implemented literally as D9 Leo, Scorpio or Aquarius. Simultaneous alternatives are one correlated observation and are not a guaranteed factual outcome."], maturity: "located", testObligations: ["each named seventh sign", "own-Navamsa gate", "malefic-aspect gate", "Mars eighth gate", "each named Mars Navamsa", "wrong Mars house", "wrong Mars Navamsa", "alternative deduplication"] },
  { family: "prashna:classical-travel-rising-mode", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IV, Travels in General, verse 1"], statement: "For a travel query, a movable ascendant supports movement, a fixed ascendant opposes it, and the first or second half of a dual sign acts respectively like movable or fixed.", requiredInputs: ["ascendant sign", "degree within dual sign"], effect: "qualify", exceptions: ["Other travel and return combinations remain independent testimony; this rule alone is not timing or a guaranteed event."], maturity: "located", testObligations: ["four movable signs", "four fixed signs", "four dual signs first half", "four dual signs second half", "15-degree boundary"] },
  { family: "prashna:classical-travel-verse-2-direct", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IV, verse 2"], statement: "A direct Sun, Saturn, Mercury or Venus occupying a movable ascendant supports early travel.", requiredInputs: ["ascendant modality", "ascendant occupants", "retrograde state"], effect: "support", exceptions: ["The same verse explicitly reverses the result when the qualifying occupant is retrograde."], maturity: "located", testObligations: ["each qualifying planet", "non-qualifying planet", "non-movable ascendant", "direct state"] },
  { family: "prashna:classical-travel-verse-2-retrograde", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IV, verse 2 retrograde clause"], statement: "A qualifying verse-2 occupant in retrograde motion opposes travel despite occupying a movable ascendant.", requiredInputs: ["ascendant modality", "ascendant occupant", "retrograde state"], effect: "oppose", exceptions: ["Only the planets named in verse 2 activate this clause."], maturity: "located", testObligations: ["retrograde Mercury", "retrograde Venus", "retrograde Saturn", "direct exclusion"] },
  { family: "prashna:classical-travel-verse-3", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IV, verse 3"], statement: "Jupiter, Mercury, Venus or the Sun occupying a fixed ascendant supports interruption of the journey and return.", requiredInputs: ["fixed ascendant", "ascendant occupants"], effect: "oppose", exceptions: ["This is adverse to continuing travel but supportive if the actual question concerns return."], maturity: "located", testObligations: ["each qualifying planet", "movable exclusion", "non-qualifying occupant"] },
  { family: "prashna:classical-travel-verse-4-eleventh", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IV, verse 4"], statement: "Sun, Jupiter, Mercury or Venus in the eleventh supports an early journey.", requiredInputs: ["planet houses"], effect: "support", exceptions: ["The same named planets in the twelfth instead indicate breaking the journey and returning."], maturity: "located", testObligations: ["each named planet in eleventh", "wrong planet", "wrong house"] },
  { family: "prashna:classical-travel-verse-4-twelfth", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IV, verse 4"], statement: "Sun, Jupiter, Mercury or Venus in the twelfth supports breaking the journey and returning.", requiredInputs: ["planet houses"], effect: "oppose", exceptions: ["This is adverse to continuing travel but supportive if the actual question concerns return."], maturity: "located", testObligations: ["each named planet in twelfth", "wrong planet", "wrong house"] },
  { family: "prashna:classical-travel-verse-5-no-return", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IV, verse 5"], statement: "A fixed ascendant aspected by both Jupiter and Saturn supplies non-return testimony for a distant traveller.", requiredInputs: ["ascendant modality", "Jupiter graha drishti", "Saturn graha drishti"], effect: "oppose", exceptions: ["Both aspects are required; this is one traditional testimony rather than certainty."], maturity: "reproduced", testObligations: ["all fixed signs", "both aspects", "either missing aspect", "non-fixed ascendant"] },
  { family: "prashna:classical-travel-verse-6-no-travel", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IV, verse 6"], statement: "With a fixed ascendant, houses 5, 6 and 9 must each contain a natural malefic that receives another natural malefic's graha drishti to supply the verse's no-travel testimony.", requiredInputs: ["ascendant modality", "conditional natural nature", "houses 5, 6 and 9", "malefic graha drishti"], effect: "oppose", exceptions: ["The enumerated houses are interpreted conjunctively; self-aspect is excluded; the movable-sign sentence is already represented by verse 1."], maturity: "located", testObligations: ["all three houses populated and aspected", "each missing house", "unaspected target", "self exclusion", "fixed gate"] },
  { family: "prashna:classical-travel-verses-8-9-timing-candidates", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IV, verses 8–9"], statement: "The strongest planet's sign-count from the ascendant gives months, multiplied by one, two or three for movable, fixed or dual Navamsa respectively; until strongest-planet selection is source-verified, every planet is exposed only as a neutral candidate.", requiredInputs: ["planet house count", "D9 sign and modality", "source-verified strongest planet"], effect: "classify", exceptions: ["The engine does not choose the strongest planet and does not emit a timing window from candidates alone."], maturity: "reproduced", testObligations: ["all twelve house counts", "three Navamsa multipliers", "all seven candidates", "no automatic selection", "no timing window"] },
  { family: "prashna:classical-travel-verse-10-retrograde-search", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter IV, verse 10"], statement: "Search a bounded interval for retrograde windows of the seventh-house lord, which the source associates with a traveller's return, and refine bracketed station boundaries below the sampling interval.", requiredInputs: ["ascendant sign", "seventh lord", "search interval and resolution", "boundary tolerance", "shared sidereal ephemeris"], effect: "classify", exceptions: ["Interval-edge windows remain explicitly truncated; the window is astronomical research testimony and not a guaranteed return date."], maturity: "reproduced", testObligations: ["all possible seventh lords", "direct-only body", "retrograde window", "one-minute direct/retrograde separation", "interval clipping and truncation", "invalid interval/resolution", "50,000-point guard", "no guaranteed wording"] },
  { family: "prashna:classical-marriage-promise-cluster", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter XII, verses 1, 4 and 11–13"], statement: "The overlapping Moon-house, aspect, strong-Venus and movable-sign clauses form one correlated marriage-promise testimony; every matched clause is exposed without multiplying its score.", requiredInputs: ["Moon and ascendant signs/houses", "Sun/Jupiter/Mercury/Venus graha drishti", "Venus own/exaltation dignity", "angular natural malefics"], effect: "support", exceptions: ["Verse 1's separate benefics-in-quadrants-and-trines phrase has ambiguous count grammar and is not assigned an invented threshold; immediate/without-delay wording does not create a date; verse 12 strong Venus is narrowly implemented as own-sign or exalted."], maturity: "reproduced", testObligations: ["verse 1 allowed Moon houses", "all three named aspectors", "missing aspector", "verse 4 Jupiter aspect", "verse 11 no-other-aspector refinement", "verse 12 both ascendant targets and strength gate", "verse 13 every conjunctive gate", "multi-verse deduplication"] },
  { family: "prashna:classical-marriage-obstacle-cluster", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter XII, verses 4, 11 and 12 malefic-contact clauses"], statement: "Natural-malefic association or aspect to the Moon in the stated configurations, or malefic aspect to Moon/Mercury in the ascendant under verse 12, supplies one correlated obstacle testimony.", requiredInputs: ["Moon house", "Moon/Mercury ascendant occupancy", "conditional natural nature", "association", "graha drishti"], effect: "oppose", exceptions: ["The overlapping verses contribute one observation and one weight; this indicates traditional obstruction testimony, not impossibility."], maturity: "reproduced", testObligations: ["malefic association", "malefic aspect", "verse 12 Moon target", "verse 12 Mercury target", "conditional Moon/Mercury nature", "no contact", "multi-verse deduplication"] },
  { family: "prashna:classical-marriage-saturn-seventh-parity", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Marriage chapter, verse 3"], statement: "Saturn in the seventh supports marriage when its sign is even and opposes it when its sign is odd.", requiredInputs: ["Saturn house", "sign parity"], effect: "qualify", exceptions: ["This remains one traditional testimony and is not converted into certainty."], maturity: "reproduced", testObligations: ["six even signs", "six odd signs", "Saturn outside seventh"] },
  { family: "prashna:classical-gains-verse-1-support", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter III, verse 1"], statement: "Natural benefics in houses 3, 5, 7 or 11 support gain.", requiredInputs: ["natural nature", "planet houses"], effect: "support", exceptions: ["Multiple qualifying benefics form one correlated testimony."], maturity: "reproduced", testObligations: ["each allowed house", "wrong house", "conditional Moon and Mercury", "deduplication"] },
  { family: "prashna:classical-gains-verse-1-obstacle", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter III, verse 1"], statement: "Natural malefics in houses 3, 5, 7 or 11 oppose the desired gain.", requiredInputs: ["natural nature", "planet houses"], effect: "oppose", exceptions: ["This is a genuine opposing axis and is not erased when benefic testimony also exists."], maturity: "reproduced", testObligations: ["each allowed house", "wrong house", "mixed simultaneous testimony"] },
  { family: "prashna:classical-gains-verse-1-prosperity", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter III, verse 1"], statement: "Natural benefics in houses 7 or 10 support status and position, while benefics in houses 1, 2 or 5 support honour and wealth.", requiredInputs: ["natural nature", "planet houses"], effect: "support", exceptions: ["Overlapping status and wealth matches are aggregated once."], maturity: "reproduced", testObligations: ["status houses", "honour/wealth houses", "overlap aggregation"] },
  { family: "prashna:classical-gains-verse-2-woman", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter III, verse 2"], statement: "Moon in house 2, 3, 6, 7, 10 or 11 receiving natural-benefic aspect supports gain through a woman.", requiredInputs: ["Moon house", "natural-benefic graha drishti"], effect: "support", exceptions: ["No result is inferred without both placement and aspect."], maturity: "reproduced", testObligations: ["all six houses", "benefic aspect", "missing aspect", "wrong house"] },
  { family: "prashna:classical-gains-verse-2-fear-loss", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter III, verse 2"], statement: "Moon in house 1, 3, 5, 8 or 9 receiving natural-malefic aspect supplies fear, failure or expenditure testimony.", requiredInputs: ["Moon house", "natural-malefic graha drishti"], effect: "oppose", exceptions: ["House 3 belongs to both the supportive and adverse lists; aspector nature preserves the two axes."], maturity: "reproduced", testObligations: ["all five houses", "malefic aspect", "missing aspect", "house-3 mixed case"] },
  { family: "prashna:classical-gains-verse-2-benefic-reversal", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter III, verse 2, final sentence"], statement: "Natural benefics in the verse's loss-sensitive houses 1, 3, 5, 8 or 9 instead support status, wealth and property.", requiredInputs: ["natural nature", "planet houses"], effect: "support", exceptions: ["The antecedent ‘these houses’ is interpreted as the immediately preceding five-house list; all matches are aggregated once."], maturity: "located", testObligations: ["five-house list", "wrong house", "correlated aggregation"] },
  { family: "prashna:classical-gains-verse-3-quick", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter III, verse 3"], statement: "Quick gain requires the complete arrangement: every natural benefic in a quadrant or trine and every natural malefic in houses 3, 6 or 11.", requiredInputs: ["conditional natural nature of every planet", "planet houses"], effect: "support", exceptions: ["A single matching planet is insufficient; the opposite arrangement is not scored until its grammar is independently resolved."], maturity: "reproduced", testObligations: ["complete arrangement", "one misplaced benefic", "one misplaced malefic", "conditional nature"] },
  { family: "prashna:classical-gains-verse-4-immediate", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter III, verse 4"], statement: "Moon in house 4 or 7 together with Sun in house 1 or 10 supports immediate monetary gain.", requiredInputs: ["Moon house", "Sun house"], effect: "support", exceptions: ["Immediate is preserved as source wording and not converted into a date."], maturity: "reproduced", testObligations: ["four Cartesian combinations", "wrong Moon house", "wrong Sun house", "no timing window"] },
  { family: "prashna:classical-gains-verse-5-modality", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter III, verse 5"], statement: "A fixed rising sign supports acquisition of status or post, a movable sign opposes it, and a dual sign carries both results.", requiredInputs: ["ascendant sign modality"], effect: "qualify", exceptions: ["The dual-sign branch remains neutral/mixed rather than being forced positive or negative."], maturity: "reproduced", testObligations: ["four fixed signs", "four movable signs", "four dual signs"] },
  { family: "prashna:classical-abroad-return-cluster", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter VI, verses 1–3 and 5–6"], statement: "The chapter's overlapping planet-house combinations support return of a person abroad; all matched return clauses are exposed but contribute one correlated observation and one weight.", requiredInputs: ["seven classical planet houses", "conditional natural nature", "quadrants and trines"], effect: "support", exceptions: ["Quick return, happy return, return with gains and entering home remain refinements, not dates; nodes are not inserted into the source's unspecified classical all-planets clauses."], maturity: "reproduced", testObligations: ["verse 1 complete placement", "verse 2 both alternatives", "verse 3 no-malefic-angle gate and gain refinement", "verse 5 both branches", "verse 6 complete arrangement", "multi-verse deduplication"] },
  { family: "prashna:classical-abroad-verse-10-safe", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter VI, verse 10"], statement: "A natural benefic in the ninth supplies untroubled-journey testimony.", requiredInputs: ["conditional natural nature", "planet houses"], effect: "support", exceptions: ["Multiple benefics are aggregated once; this is not a safety guarantee."], maturity: "reproduced", testObligations: ["benefic ninth", "wrong house", "conditional Moon/Mercury", "deduplication"] },
  { family: "prashna:classical-abroad-verse-10-trouble", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter VI, verse 10"], statement: "A natural malefic in the ascendant supplies difficulty testimony for the journey.", requiredInputs: ["conditional natural nature", "planet houses"], effect: "oppose", exceptions: ["This does not imply death, detention or a specific event; multiple malefics are aggregated once."], maturity: "reproduced", testObligations: ["malefic ascendant", "wrong house", "mixed with ninth benefic", "deduplication"] },
  { family: "prashna:classical-disease-verse-3-hardship", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter VIII, verse 3"], statement: "Moon or Mercury in the ascendant receiving natural-malefic graha drishti supplies traditional hardship testimony.", requiredInputs: ["Moon and Mercury houses", "conditional natural nature", "graha drishti"], effect: "oppose", exceptions: ["This is not a diagnosis or medical prognosis; multiple contacts form one observation."], maturity: "reproduced", testObligations: ["Moon target", "Mercury target", "each aspect mode", "missing aspect", "conditional Mercury nature", "deduplication"] },
  { family: "prashna:classical-disease-recovery-cluster", tradition: "classical", sourceIds: ["book-daivajna-vallabha"], locators: ["Daivajna Vallabha, Chapter VIII, verses 4, 6 and 7"], statement: "The chapter's multi-gate benefic arrangements, benefic ascendant aspect, full-Moon/Jupiter contact, and angular Jupiter–Venus combinations supply traditional recovery testimony; all matching alternatives contribute one correlated observation.", requiredInputs: ["conditional natural nature", "planet houses from ascendant and Moon", "graha drishti", "full-Moon phase"], effect: "support", exceptions: ["Verse 4's enumerated houses are read literally as all three populated and its final ‘same places’ as at least one benefic in an Upachaya from Moon; because verse 6 names the Moon separately, its plural benefics are read as all other natural benefics within the allowed house set; this is not medical advice, diagnosis or prognosis."], maturity: "located", testObligations: ["verse 4 every gate and each failed gate", "verse 6 both alternatives", "verse 7 both alternatives", "full-Moon boundary", "multi-verse deduplication", "medical disclaimer"] },
  { family: "prashna:systems-mep", tradition: "systems-approach", sourceIds: ["book-application-prasna-astrology"], locators: ["Most Effective Point (MEP) section"], statement: "Project the ascendant's rising degree as the most effective point of every house.", requiredInputs: ["ascendant degree"], effect: "classify", exceptions: ["This convention belongs only to the Systems' Approach namespace."], maturity: "located", testObligations: ["degree projection", "sign boundaries"] },
  { family: "prashna:systems-functional-nature", tradition: "systems-approach", sourceIds: ["book-application-prasna-astrology"], locators: ["Functional Malefic Planets table for all twelve ascendants"], statement: "Lords whose moolatrikona signs fall in houses 6, 8 or 12 are functional malefics together with Rahu and Ketu; the remaining classical planets are functional benefics.", requiredInputs: ["ascendant sign", "moolatrikona sign registry"], effect: "classify", exceptions: ["This functional classification is Systems' Approach-specific and must not replace another tradition's natural classification."], maturity: "reproduced", testObligations: ["all twelve printed table rows", "functional-benefic complement", "Rahu and Ketu in every row"] },
  { family: "prashna:systems-mmp", tradition: "systems-approach", sourceIds: ["book-application-prasna-astrology"], locators: ["Most Malefic Planet (MMP) section and twelve-ascendant table"], statement: "The eighth-house moolatrikona lord is MMP; if absent use the twelfth-house moolatrikona lord, and if that is also absent use Ketu.", requiredInputs: ["ascendant sign", "moolatrikona sign registry"], effect: "classify", exceptions: ["MMP identifies precedence among afflictors; it is not by itself an event denial."], maturity: "reproduced", testObligations: ["eighth-house branch", "twelfth-house fallback", "Ketu fallback", "all twelve printed table rows"] },
  { family: "prashna:systems-close-affliction-", tradition: "systems-approach", sourceIds: ["book-application-prasna-astrology", "web-systems-approach-planetary-aspects"], locators: ["Application of Prasna Astrology: Conjunctions and Aspects; MEP; Afflictions sections", "Systems' Approach General Terminology: Planetary Aspect (yournetastrologer.com/terminology.htm)"], statement: "A functional malefic reaching the projected event-house MEP by conjunction or a declared full aspect within five longitudinal degrees supplies adverse testimony, with severity increasing toward exactness.", requiredInputs: ["functional lordship", "planet house and degree", "planet-specific full-aspect offsets", "target-house MEP", "orb"], effect: "oppose", exceptions: ["Strong-planet and weak-planet severity distinctions require separate strength evaluation; an MMP contact must remain identified."], maturity: "located", testObligations: ["conjunction", "universal seventh aspect", "Mars fourth/eighth", "Saturn third/tenth", "Jupiter/Rahu/Ketu fifth/ninth", "exact five-degree boundary", "outside orb", "MMP identification"] },
  { family: "prashna:systems-close-planet-affliction-", tradition: "systems-approach", sourceIds: ["book-application-prasna-astrology", "web-systems-approach-planetary-aspects"], locators: ["Application of Prasna Astrology: Afflictions to the planets or houses", "Worked Chart 36: Moon closely afflicted by Ketu's aspect", "Systems' Approach General Terminology: Planetary Aspect"], statement: "A functional malefic reaching a target planet by close conjunction or a declared full aspect within five longitudinal degrees afflicts that planet, with the same graded influence scale used for house MEPs.", requiredInputs: ["functional nature", "afflicter and target signs/degrees", "planet-specific full aspects", "five-degree scale"], effect: "oppose", exceptions: ["A planet cannot afflict itself; planetary affliction remains distinct from intrinsic weakness; exact five degrees has zero influence."], maturity: "reproduced", testObligations: ["worked Chart 36 Ketu–Moon ninth aspect", "conjunction", "full special aspect", "one-to-four-degree scale", "five-degree exclusion", "self exclusion", "non-functional-malefic exclusion"] },
  { family: "prashna:systems-weak-event-lord", tradition: "systems-approach", sourceIds: ["book-application-prasna-astrology"], locators: ["Analysing Strength of Planets; Measuring the Strength: Infancy or Old Age"], statement: "A planet is weak through debilitation, combustion, infancy/old age, dusthana placement, divisional debilitation, or occupation of the moolatrikona sign of another weak planet; a weak event lord cannot fully protect its significations.", requiredInputs: ["D1 placement and dignity", "combustion", "degree in sign", "whole-sign house", "divisional signs", "weak-dispositor dependency"], effect: "oppose", exceptions: ["Weakness is distinct from functional maleficence; the age scale describes power and is not an event probability."], maturity: "located", testObligations: ["infancy 0–5 degrees", "old age 25–30 degrees", "debilitation", "combustion", "dusthana", "divisional debilitation", "transitive weak dispositor"] },
  { family: "prashna:systems-operating-period-profile", tradition: "systems-approach", sourceIds: ["book-application-prasna-astrology"], locators: ["Identifying Results of Main or Sub Period Lords, items 1–3; Interaction Between the Sub Period and Transit Results"], statement: "An operating sub-period activates the planet's general significations, its moolatrikona-owned house and its occupied house; functional nature and weakness remain explicit qualifiers.", requiredInputs: ["Vimshottari operating lords", "ascendant", "moolatrikona registry", "planet placement", "functional nature", "weakness profile"], effect: "classify", exceptions: ["The favorable/adverse synthesis in the available OCR is corrupt and is not reconstructed; nodes have no moolatrikona-owned house in this convention."], maturity: "located", testObligations: ["main/sub/sub-sub levels", "classical planet moolatrikona house", "node null moolatrikona house", "occupied house", "functional nature", "weakness retained"] },
  { family: "prashna:systems-period-transit-interaction", tradition: "systems-approach", sourceIds: ["book-application-prasna-astrology"], locators: ["Analysing Capability of Planets to Bless with Their Significations", "Identifying Transit Influences", "Interaction Between the Sub Period and Transit Results, Sagittarius/Venus example"], statement: "The sub-period lord sets the trend; functional-malefic transit conjunctions or declared aspects within five degrees activate pressure at the relevant house MEP, the natal sub-period-lord position, or the transit sub-period-lord position. A functional benefic can bless fully only when strong in both radix and transit.", requiredInputs: ["radix and transit charts", "ascendant-specific functional nature", "sub-period lord", "event-house MEP", "natal and transit sub-period-lord positions", "full aspect offsets", "weakness profiles"], effect: "classify", exceptions: ["Self-contact of a functional-malefic sub-period lord to its own natal/transit position is not double-counted; a single one-hour snapshot is not a transit calendar; exact five degrees has zero influence under the source scale."], maturity: "located", testObligations: ["all three activation points", "conjunction", "special full aspect", "five-degree boundary", "self-contact exclusion", "radix strength", "transit strength", "neutral consultation snapshot"] },
  { family: "prashna:systems-forward-transit-calendar", tradition: "systems-approach", sourceIds: ["book-application-prasna-astrology"], locators: ["Identifying Transit Influences", "Interaction Between the Sub Period and Transit Results"], statement: "Search a bounded interval for close functional-malefic transit conjunctions or full aspects to the event-house MEP and the natal or moving sub-period lord, preserving each activation point as a separate window, refining bracketed ingress/egress, and continuously minimizing the degree difference inside the best sampled peak bracket.", requiredInputs: ["radix", "sub-period lord", "event house", "search interval", "sampling resolution", "boundary and peak tolerance", "shared sidereal ephemeris"], effect: "classify", exceptions: ["Interval-edge boundaries are explicitly truncated; the sampled peak is retained beside the refined local peak; self-contact is excluded; a contact window is pressure testimony rather than an event promise or probability."], maturity: "reproduced", testObligations: ["actual ephemeris search", "three activation-point types", "contiguous-window grouping", "bracketed ingress and egress refinement", "interval-edge truncation", "sampled peak retention", "continuous peak improvement", "conjunction and special-aspect peaks", "peak inside refined window", "self exclusion", "empty sub-period", "invalid interval", "resolution and 50,000-point guards", "no outcome claim"] },
  { family: "prashna:lord-angular", tradition: "shared", sourceIds: ["book-daivajna-vallabha", "book-neelakanta-prasna-tantra"], locators: ["General house-strength passages; exact rule locator pending"], statement: "An event lord in an angle is supporting structural testimony.", requiredInputs: ["event lord", "whole-sign house"], effect: "support", exceptions: ["Dignity, affliction and school-specific aspects must be judged separately."], maturity: "structural", testObligations: ["houses 1, 4, 7, 10", "non-angular houses"] },
  { family: "prashna:lord-dusthana", tradition: "shared", sourceIds: ["book-daivajna-vallabha", "book-neelakanta-prasna-tantra"], locators: ["Bhava-prasna passages; exact rule locator pending"], statement: "An event lord in houses 6, 8 or 12 is challenging structural testimony.", requiredInputs: ["event lord", "whole-sign house"], effect: "oppose", exceptions: ["Topic-specific ownership and derived-house rules can change the meaning."], maturity: "structural", testObligations: ["houses 6, 8, 12", "other houses"] },
  { family: "prashna:lord-dignity", tradition: "shared", sourceIds: ["book-daivajna-vallabha", "book-neelakanta-prasna-tantra"], locators: ["Planetary avasthas / Chapter I"], statement: "Own-sign or exaltation dignity strengthens the relevant lord.", requiredInputs: ["event lord longitude", "dignity table"], effect: "support", exceptions: ["Combustion, defeat and affliction are independent qualifiers."], maturity: "located", testObligations: ["own sign", "exaltation", "ordinary sign"] },
  { family: "prashna:lord-debilitated", tradition: "shared", sourceIds: ["book-daivajna-vallabha", "book-neelakanta-prasna-tantra"], locators: ["Planetary avasthas / Chapter I"], statement: "Debilitation weakens the relevant lord.", requiredInputs: ["event lord longitude", "dignity table"], effect: "oppose", exceptions: ["Cancellation or school-specific recovery conditions are not inferred."], maturity: "located", testObligations: ["exact debilitation sign", "other signs"] },
  { family: "prashna:lord-combust", tradition: "shared", sourceIds: ["book-neelakanta-prasna-tantra"], locators: ["Planetary avasthas and bhava-prasna affliction passages"], statement: "Combustion qualifies the relevant lord as afflicted.", requiredInputs: ["planet-Sun separation", "combustion convention"], effect: "oppose", exceptions: ["Planet-specific combustion limits must match the chart engine convention."], maturity: "structural", testObligations: ["inside limit", "boundary", "outside limit"] },
  { family: "prashna:benefic-", tradition: "shared", sourceIds: ["book-daivajna-vallabha", "book-prasna-marga-raman"], locators: ["Prasna Marga Part II, glossary: Waning Moon", "General good-and-bad-result passages"], statement: "A conditionally natural benefic occupying the relevant house is supporting testimony. The Moon is waxing/strong from Shukla 8 through Krishna 7.", requiredInputs: ["event house", "occupant", "lunar-day index when occupant is Moon", "Mercury association when occupant is Mercury"], effect: "support", exceptions: ["Mercury becomes adverse with natural-malefic association; Krishna 8 through Shukla 7 is the waning/weak interval."], maturity: "located", testObligations: ["fixed benefics", "Mercury unafflicted", "Shukla 7/8 boundary", "Krishna 7/8 boundary"] },
  { family: "prashna:malefic-", tradition: "shared", sourceIds: ["book-daivajna-vallabha", "book-prasna-marga-raman"], locators: ["Prasna Marga Part II, glossary: Waning Moon", "General good-and-bad-result passages"], statement: "A conditionally natural malefic occupying the relevant house is challenging testimony. The Moon is waning/weak from Krishna 8 through Shukla 7.", requiredInputs: ["event house", "occupant", "lunar-day index when occupant is Moon", "Mercury association when occupant is Mercury"], effect: "oppose", exceptions: ["Upachaya and topic-specific exceptions must be applied separately."], maturity: "located", testObligations: ["fixed malefics", "Mercury afflicted", "Shukla 7/8 boundary", "Krishna 7/8 boundary", "upachaya exception"] },
  { family: "prashna:saturn-pressure", tradition: "shared", sourceIds: ["book-prasna-marga-raman"], locators: ["Saturn topic passages; exact locator pending"], statement: "Saturn in the relevant house supplies delay or pressure testimony.", requiredInputs: ["event house", "Saturn placement"], effect: "oppose", exceptions: ["Do not convert pressure automatically into denial."], maturity: "structural", testObligations: ["Saturn present", "Saturn absent"] },
  { family: "prashna:moon-position", tradition: "shared", sourceIds: ["book-daivajna-vallabha", "book-neelakanta-prasna-tantra"], locators: ["Moon testimony passages"], statement: "The Moon's house provides immediate supporting, opposing or neutral context.", requiredInputs: ["Moon house"], effect: "qualify", exceptions: ["Moon phase, aspects and application must be judged independently."], maturity: "structural", testObligations: ["angles", "difficult houses", "other houses"] },
  { family: "prashna:tajaka-shared-lord", tradition: "tajaka", sourceIds: ["book-neelakanta-prasna-tantra"], locators: ["Chapter II, bhava-prasna significator rules"], statement: "One planet ruling querent and event directly connects their significations.", requiredInputs: ["ascendant lord", "event lord"], effect: "support", exceptions: ["Dignity and affliction still qualify delivery."], maturity: "located", testObligations: ["same lord", "different lords"] },
  { family: "prashna:tajaka-ithasala-candidate", tradition: "tajaka", sourceIds: ["book-neelakanta-prasna-tantra"], locators: ["Chapter IV, stanzas 52–55"], statement: "A faster planet applying to a slower planet within their deepthamsa forms Ithasala; within one degree it is Poorna.", requiredInputs: ["two longitudes", "future motion", "deepthamsas", "aspect geometry"], effect: "support", exceptions: ["Interference, retrogression and topic-specific conditions remain separate."], maturity: "located", testObligations: ["applying", "separating", "Poorna", "orb boundary", "each aspect"] },
  { family: "prashna:tajaka-easarapha-candidate", tradition: "tajaka", sourceIds: ["book-neelakanta-prasna-tantra"], locators: ["Chapter IV, stanza 56"], statement: "A faster planet separating from a slower planet forms Easarapha/Musaripha and is adverse testimony.", requiredInputs: ["two longitudes", "future motion", "deepthamsas", "aspect geometry"], effect: "oppose", exceptions: ["Topic-specific rules may describe what has already passed rather than simple denial."], maturity: "located", testObligations: ["separating", "applying exclusion", "orb boundary"] },
  { family: "prashna:tajaka-kamboola-candidate", tradition: "tajaka", sourceIds: ["book-neelakanta-prasna-tantra"], locators: ["Chapter IV, stanza 61 and Raman's grade notes"], statement: "Ithasala between the two lords plus Moon's Ithasala with either produces Kamboola; its named grade is determined separately from D1 and specified divisional dignities.", requiredInputs: ["lord-lord Ithasala", "Moon-lord Ithasala", "D1 dignity", "D3/D9/D12 signs for applicable grades"], effect: "support", exceptions: ["Madhyamottama/Uttama variants mentioning Hadda and Adhama requiring Panchadhikara remain unresolved until those calculations exist."], maturity: "located", testObligations: ["Moon with first lord", "Moon with second lord", "no Moon contact", "Uttamottama", "Uttamadhama", "D9/D12 Madhyamottama", "D3/D9 Madhyama", "unresolved Hadda/Panchadhikara"] },
  { family: "prashna:tajaka-career-kamboola-stanza-112", tradition: "tajaka", sourceIds: ["book-neelakanta-prasna-tantra"], locators: ["Bhava Prasna, tenth-house questions, stanza 112 and note"], statement: "When the ascendant and tenth lords form Ithasala and the Moon forms Ithasala with either while angular, career Kamboola supports a good position; an own-sign angular Moon supplies the text's stronger enlarged-position qualification.", requiredInputs: ["horary ascendant sign", "ascendant lord", "tenth lord", "two applying in-deepthamsa relations", "Moon house", "Moon sign lord"], effect: "support", exceptions: ["The rule is career-specific; its result scale is preserved as textual testimony, not converted into certainty. Generic Kamboola is not separately scored when this specific rule fires."], maturity: "located", testObligations: ["angular Moon", "succedent/cadent Moon exclusion", "missing lord-lord Ithasala", "missing Moon Ithasala", "own-sign Moon stronger scale", "no duplicate generic scoring"] },
  { family: "prashna:tajaka-career-exchange-stanza-109", tradition: "tajaka", sourceIds: ["book-neelakanta-prasna-tantra"], locators: ["Bhava Prasna, tenth-house questions, stanza 109 and note"], statement: "An exchange between the ascendant and tenth lords supports career acquisition without effort when both planets are unafflicted.", requiredInputs: ["horary ascendant sign", "ascendant lord sign", "tenth lord sign", "malefic conjunctions", "chapter-IV in-deepthamsa aspects"], effect: "support", exceptions: ["The two required exchange partners are not counted as external afflictors of one another. Rahu and Ketu are tested only by same-sign conjunction because the installed edition supplies no node deepthamsa. If another affliction is found the support rule abstains; no denial is inferred."], maturity: "located", testObligations: ["exact exchange", "one-way placement exclusion", "clear exchange", "malefic conjunction gate", "malefic aspect gate", "exchange partners not self-cancelling", "no reverse denial"] },
  { family: "prashna:tajaka-object-realisation-stanza-113", tradition: "tajaka", sourceIds: ["book-neelakanta-prasna-tantra"], locators: ["Bhava Prasna, On Realising the Object, stanza 113 and 31 January 1969 job-interview example"], statement: "Object realisation is obstructed when the dispositor of the ascendant lord occupies the 6th, 8th or 12th; combustion of the ascendant lord indicates great difficulty, and a 4th/10th sign relationship involving the dispositor indicates strife or quarrels.", requiredInputs: ["ascendant sign and lord", "ascendant-lord sign dispositor", "dispositor house", "ascendant-lord combustion", "sign-based 4th/10th square geometry"], effect: "oppose", exceptions: ["The printed example treats the Moon ten signs from Jupiter as square even outside their combined deepthamsa, so this topic rule uses sign geometry. The three correlated clauses are aggregated into one observation and do not erase independent support."], maturity: "reproduced", testObligations: ["each dusthana", "non-dusthana", "combustion", "square both directions", "degree offset does not cancel sign square", "31 January 1969 chart", "multi-clause aggregation", "independent support preserved"] },
  { family: "prashna:tajaka-nakta-candidate-", tradition: "tajaka", sourceIds: ["book-neelakanta-prasna-tantra"], locators: ["Chapter IV, stanza 57 and explanatory Mercury–Moon–Jupiter example"], statement: "With no direct in-deepthamsa aspect, a faster intermediary applying to both lords forms Nakta when it perfects first with the faster principal and then carries the light to the slower principal.", requiredInputs: ["source speed order", "two applying intermediary aspects", "perfection order", "absence of direct in-orb aspect"], effect: "support", exceptions: ["Stationary, separating, crossed-within-sample and reversed-perfection contacts are excluded; topic-specific outcome and dignity remain separate."], maturity: "reproduced", testObligations: ["faster intermediary", "both contacts applying", "donor-before-receiver perfection", "direct-aspect exclusion", "wrong speed", "stationary", "separating", "overshoot/reversed order"] },
  { family: "prashna:tajaka-yamaya-candidate-", tradition: "tajaka", sourceIds: ["book-neelakanta-prasna-tantra"], locators: ["Chapter IV, stanza 60 and explanatory Venus–Jupiter–Moon example"], statement: "With no direct in-deepthamsa aspect, a slower intermediary forms Yamaya when both faster principals apply to it as collector.", requiredInputs: ["source speed order", "two applying contacts to slower collector", "absence of direct in-orb aspect"], effect: "support", exceptions: ["Stationary or separating contacts are excluded; topic-specific outcome and dignity remain separate."], maturity: "reproduced", testObligations: ["slower collector", "both contacts applying", "direct-aspect exclusion", "wrong speed", "stationary", "separating"] },
  { family: "prashna:nadi-seed-ascendant", tradition: "prashna-nadi", sourceIds: ["book-umang-taneja-prashna-nadi", "book-kp-reader-vi-horary"], locators: ["Reader VI 1–249 procedure: beginning of the selected sub is ascendant; other cusps calculated for latitude", "Taneja seed and Raphael's Table of Houses procedure"], statement: "The selected number determines a zodiacal subdivision whose beginning is the effective first cusp; the other Placidus cusps are calculated for the judgment latitude.", requiredInputs: ["integer 1–249", "KP subdivision table", "judgment latitude", "KP ayanamsa"], effect: "classify", exceptions: ["The segment midpoint is descriptive only and must not replace the source-defined beginning; polar Placidus failure causes abstention."], maturity: "reproduced", testObligations: ["all 249 segments", "continuity", "boundaries", "invalid inputs", "beginning-not-midpoint anchor", "Reader VI number-203 cusp table", "polar abstention"] },
  { family: "prashna:nadi-node-signification", tradition: "prashna-nadi", sourceIds: ["book-umang-taneja-prashna-nadi"], locators: ["Node house-coordinate procedure and worked Rahu/Ketu example"], statement: "Rahu and Ketu signify the houses of conjoined planets, aspecting planets, their sign lord, and their own occupied house, in that stated sequence; they receive no sign lordship of their own.", requiredInputs: ["Nirayana Bhava Chalit cusps", "planet positions", "Nadi aspect table", "sign lords"], effect: "classify", exceptions: ["This is the Taneja Prashna Nadi convention and must not be silently substituted for another KP node hierarchy."], maturity: "located", testObligations: ["conjoined representative", "aspecting representative", "sign-lord representative", "occupied house", "deduplication", "no node lordship"] },
  { family: "prashna:kp-ruling-planets", tradition: "prashna-nadi", sourceIds: ["book-kp-reader-vi-horary"], locators: ["Ruling Planets section: day lord, Lagna star/sign lords, Moon star/sign lords, node agents and retrograde exclusions"], statement: "KP ruling planets are the day lord, ascendant star and sign lords, and Moon star and sign lords; nodes occupying a sign of a ruling lord are included as its agents, candidates in a retrograde planet's constellation are rejected, and a retrograde candidate itself indicates delay.", requiredInputs: ["weekday", "KP ascendant", "KP Moon", "star lords", "node signs", "retrograde state"], effect: "classify", exceptions: ["Sun and Moon are never retrograde; KP Reader VI treats the steadily reverse-moving nodes as never retrograde for this filter."], maturity: "located", testObligations: ["five source roles", "duplicate role collapse", "node agent", "retrograde star-lord rejection", "retrograde candidate delay", "node retrograde exclusion"] },
  { family: "prashna:kp-node-representation", tradition: "prashna-nadi", sourceIds: ["book-kp-reader-vi-horary"], locators: ["Reader VI worked lottery judgment: nodes firstly give conjoined planets, then star lord, aspecting planets, and sign lord"], statement: "A KP node represents conjoined planets first, then the lord of its constellation, planets aspecting it, and finally its sign lord; a duplicate representative retains its earliest precedence.", requiredInputs: ["node longitude and sign", "planet signs", "node star lord", "Vedic aspects"], effect: "classify", exceptions: ["This Reader VI hierarchy remains distinct from Taneja's Prashna Nadi sequence, which does not place the star lord second."], maturity: "located", testObligations: ["all four precedence levels", "duplicate at multiple levels", "Rahu", "Ketu"] },
  { family: "prashna:kp-event-house-", tradition: "prashna-nadi", sourceIds: ["book-kp-reader-vi-horary"], locators: ["Reader VI topic sections for marriage, child birth, examination, employment, foreign travel, litigation, lost-property recovery and health"], statement: "A topic-specific KP predicate compares the houses signified by the relevant planet or cuspal sub-lord with the source's required event houses and keeps adverse or negating houses as a separate axis.", requiredInputs: ["topic", "relevant significator or cuspal sub-lord", "signified houses"], effect: "classify", exceptions: ["A static house match is not a promise or timing verdict until the topic section's specified cusp, retrograde conditions and period/transit requirements are also satisfied."], maturity: "located", testObligations: ["all registered topics", "complete match", "missing required house", "required plus adverse mixed case", "recovery/non-recovery opposition"] },
  { family: "prashna:kp-event-house-career-employment-viswanath", tradition: "prashna-nadi", sourceIds: ["book-viswanath-prashna-remedies-vol-1"], locators: ["Prashna Astrology and Remedies Volume I, Prashna—Job and Marriage, Astro Hints—Job", "Volume I, Prashna about Job: houses favourable for getting job and conjoined-period instruction"], statement: "For paid employment, planets collectively signifying houses 2, 6, 10 and 11 are selected for their conjoined period, subject to the Prashna horoscope not negating the event.", requiredInputs: ["KP planet significator portfolios", "houses 2, 6, 10 and 11", "Dasa-Bhukti-Antara"], effect: "classify", exceptions: ["This Volume I formulation is retained independently from Reader VI's 2-6-10 employment predicate; the unspecified negation test is not invented."], maturity: "located", testObligations: ["all four houses complete", "each missing house", "collective period completion", "independent Reader VI comparison", "unspecified negation abstention"] },
  { family: "prashna:kp-operating-period-career-employment-viswanath", tradition: "prashna-nadi", sourceIds: ["book-viswanath-prashna-remedies-vol-1"], locators: ["Volume I, Prashna about Job, Analysis: Venus-Rahu-Jupiter; every DBA lord links to one or more of houses 2, 6, 10 and 11"], statement: "The operating Dasa-Bhukti-Antara lords are collectively checked for the Volume I employment houses, with every level required to contribute.", requiredInputs: ["operating KP periods", "planet significator houses", "houses 2, 6, 10 and 11"], effect: "classify", exceptions: ["The book's unspecified horoscope-negation condition remains unresolved; a complete period portfolio is therefore a candidate, not a promise."], maturity: "located", testObligations: ["Venus-Rahu-Jupiter worked structure", "every period level contributes", "all four houses completed collectively", "missing level", "no certainty wording"] },
  { family: "prashna:kp-conjoined-period-career-employment-viswanath", tradition: "prashna-nadi", sourceIds: ["book-viswanath-prashna-remedies-vol-1", "book-kp-reader-vi-horary"], locators: ["Volume I, Astro Hints—Job and Analysis: conjoined period of house significators", "Reader VI ruling-planet intersection and future conjoined-period procedure"], statement: "Future conjoined-period candidates combine Volume I's 2-6-10-11 employment portfolio with Reader VI's explicit ruling-planet intersection and retrograde gates.", requiredInputs: ["KP period timeline", "Volume I employment houses", "Reader VI ruling planets and retrograde gates"], effect: "classify", exceptions: ["This is an explicit within-school synthesis; the source-unspecified negation condition and transit delivery remain unresolved."], maturity: "located", testObligations: ["source IDs from both books", "all four employment houses", "ruling-planet intersection", "future-only intervals", "unresolved negation notice"] },
  { family: "prashna:kp-transit-pinning-career-employment-viswanath", tradition: "prashna-nadi", sourceIds: ["book-viswanath-prashna-remedies-vol-1", "book-kp-reader-vi-horary"], locators: ["Volume I employment conjoined-period candidate", "Reader VI scale-aware transit delivery examples"], statement: "Reader VI transit evidence may refine a Volume I employment period only when an explicit event-specific ruler pattern is supplied.", requiredInputs: ["Volume I period candidate", "Reader VI transit scale", "explicit ruler pattern"], effect: "classify", exceptions: ["Volume I does not state the decisive transit ruler pattern in the located passage; no pattern is inferred."], maturity: "located", testObligations: ["both-source provenance", "no inferred transit pattern", "neutral evidence only"] },
  { family: "prashna:kp-operating-period-", tradition: "prashna-nadi", sourceIds: ["book-kp-reader-vi-horary"], locators: ["Reader VI conjoined-period instructions; lost property: judge Dasa, sub-period and sub-sub-period lords; topic timing sections"], statement: "The KP-Moon-derived operating Dasa, Bhukti and Antara lords contribute their signified houses collectively to an event combination, while each level must contribute and a retrograde constellation lord blocks fructification.", requiredInputs: ["KP-corrected Moon longitude", "operating Dasa-Bhukti-Antara", "planet house portfolios", "event-house rule", "period-lord star lords", "retrograde state"], effect: "classify", exceptions: ["This reports current period structure only; it neither searches future periods nor pinpoints transit timing, and a retrograde period lord itself is labelled delay rather than automatic failure."], maturity: "located", testObligations: ["6′ correction crossing nakshatra boundary", "collective all-house completion", "each level contributes", "adverse-house mixed activation", "retrograde star-lord block", "retrograde period-lord delay", "no future window"] },
  { family: "prashna:kp-conjoined-period-", tradition: "prashna-nadi", sourceIds: ["book-kp-reader-vi-horary"], locators: ["Reader VI topic timing instructions: common planets between ruling planets and significators give results in their conjoined period; transit then pinpoints the event"], statement: "Future Antara intervals qualify as broad candidates when all three period lords are common to ruling planets and event significators, each contributes, and their collective houses complete the event predicate.", requiredInputs: ["KP Vimshottari timeline", "ruling planets", "event significator portfolios", "event-house rule", "retrograde gates", "question Julian day"], effect: "classify", exceptions: ["These broad intervals are not completed timing predictions; Reader VI requires transit pinning, rejected retrograde-star candidates are excluded, and no interval before the question moment is returned."], maturity: "located", testObligations: ["ruling/significator intersection", "collective event completion", "all three levels contribute", "future-only clipping", "retrograde-star exclusion", "transit-required marker", "no candidate case"] },
  { family: "prashna:kp-transit-pinning", tradition: "prashna-nadi", sourceIds: ["book-kp-reader-vi-horary"], locators: ["Reader VI vehicle purchase and foreign-travel examples: Sun transit pinpoints the date", "Reader VI vehicle-disposal example: Moon transit selects the day and Lagna selects the clock time", "Reader VI receipt-of-drugs example: Moon sign/star/sub/sub-sub timing", "Reader VI short-event research, trunk-call, friend-arrival and messenger-return examples: rising sign/star/sub/sub-sub identifies the minute"], statement: "After a qualifying conjoined period is found, transit evidence is examined at a scale appropriate to the worked event: Sun for a date, Moon for a day or fast delivery, and the ascendant for clock time. An event registry stores each explicitly printed ruler pattern; bounded searches group matching samples and refine bracketed ingress and egress to one minute.", requiredInputs: ["registered event-pattern ID", "timing scale", "search interval and resolution", "KP sidereal longitude of Sun, Moon or ascendant", "explicit source-located ruler levels"], effect: "classify", exceptions: ["Reader VI's worked examples use different ruler combinations and do not state a universal match-count threshold. The 1974 vehicle, 1971 travel, 1969 medicine and 1969 trunk-call examples have named historical-astronomy conflicts. The 1968 messenger civil time reproduces while its printed longitude conflicts internally; interval-edge windows are marked truncated and coarse sampling can miss a narrow subdivision."], maturity: "reproduced", testObligations: ["unique non-empty registry", "Sun date scale", "Moon day scale", "Lagna clock-time scale", "sign/star/sub/sub-sub decomposition", "1969 vehicle Moon-star reproduction", "1969 Bombay vehicle Lagna sign-star-sub reproduction", "1969 friend-arrival Taurus 22°50′ and 1:48 PM four-level reproduction", "1968 messenger 4 PM reproduction and Taurus 2°30′ subdivision conflict", "1969 trunk-call printed-longitude reproduction and civil-time conflict", "1974 vehicle Sun-sub conflict", "1971 foreign Sun-star conflict", "1969 medicine Moon-sub conflict", "bounded ephemeris sampling", "contiguous windows", "one-minute boundary refinement", "interval truncation", "empty-pattern rejection", "unknown registry ID", "search-size guard", "one category-level protocol observation", "no automatic exact-time verdict"] },
] as const;

export const PRASHNA_NON_EXECUTABLE_RULES = [
  {
    sourceId: "book-daivajna-vallabha",
    locator: "Chapter X, verses 1–2",
    status: "catalogued-not-executable",
    contentClass: "silent-query claims about a third party's sex, age, caste and sexual or marital status",
    reason: "Retained in the corpus but excluded from consultation output because isolated placements cannot establish sensitive facts about another person. Verses 3–4 and 6–13 are handled independently as bounded symbolic classifications.",
  },
  {
    sourceId: "book-daivajna-vallabha",
    locator: "Marriage chapter, verse 2 and verses 5–10",
    status: "catalogued-not-executable",
    contentClass: "third-party appearance profiling plus deterministic mortality, widowhood, sexual-character and moral-character claims from isolated placements",
    reason: "Retained in the source corpus but excluded from consultation verdicts: the claims are high-impact or profile a third party, and several target death or moral character rather than the event promise. No softened substitute is inferred.",
  },
  {
    sourceId: "book-daivajna-vallabha",
    locator: "Lost Articles chapter, identity clauses in verses 1–3 and verses 5–7",
    status: "catalogued-not-executable",
    contentClass: "thief identity, sex, age, disability and bodily-mark attribution",
    reason: "Retained for textual study but not used to accuse or profile a real person. Location/recovery rules remain independently executable.",
  },
  {
    sourceId: "book-daivajna-vallabha",
    locator: "Chapter VI, verses 4 and 7–9",
    status: "catalogued-not-executable",
    contentClass: "deterministic death, imprisonment and permanent-confinement claims about an absent third party",
    reason: "Retained for textual study but excluded from real-person consultation verdicts. The chapter's independent return and general journey-difficulty rules remain executable; no softened detention or mortality substitute is inferred.",
  },
  {
    sourceId: "book-daivajna-vallabha",
    locator: "Chapter VIII, verses 1–2, verse 5 death branch, and verse 8",
    status: "catalogued-not-executable",
    contentClass: "deterministic death and contradictory disease-course claims",
    reason: "Retained for textual study but excluded from medical consultation verdicts. Verse 8 says fixed signs mean neither death nor cure and then calls the movable result its reverse, which would combine cure with death; no medically consequential interpretation is invented.",
  },
  {
    sourceId: "book-daivajna-vallabha",
    locator: "Chapter IV, verse 7",
    status: "catalogued-not-executable",
    contentClass: "travel placement clause with missing outcome text",
    reason: "The installed translation ends ‘what is there to be told about travel’ without stating a result. Venus/Jupiter/Mercury placements in houses 2 or 12 from Lagna or Moon are preserved, but no direction or weight is invented.",
  },
  {
    sourceId: "book-neelakanta-prasna-tantra",
    locator: "Bhava Prasna, tenth-house questions, stanzas 108, 109(b), and 110–111",
    status: "catalogued-not-executable",
    contentClass: "career clauses requiring a planet-to-house favourable aspect, an unspecified benefic, or an undefined strong/weak planetary threshold",
    reason: "The readable clauses are preserved in the corpus, but the installed edition does not make the planet-to-house aspect convention or the required strength threshold algorithmically complete. Stanza 109(a), stanza 112, and stanza 113 are implemented independently; no missing input is guessed.",
  },
] as const;

export function resolvePrashnaRule(ruleId: string) {
  return PRASHNA_RULES
    .filter((rule) => ruleId === rule.family || ruleId.startsWith(rule.family))
    .sort((a, b) => b.family.length - a.family.length)[0];
}

export function prashnaRuleProvenance(ruleId: string, convention: string): RuleProvenance {
  const definition = resolvePrashnaRule(ruleId);
  if (!definition) throw new Error(`Unregistered Prashna rule: ${ruleId}`);
  const tier: JudgmentTier = definition.maturity === "reviewed" || definition.maturity === "calibrated"
    ? "citation-backed"
    : "structural-convention";
  return {
    ruleId,
    tier,
    convention,
    sourceIds: [...definition.sourceIds],
    reviewStatus: definition.maturity === "reviewed" || definition.maturity === "calibrated" ? "reviewed" : "structural-unreviewed",
    sourceLocators: [...definition.locators],
    ruleMaturity: definition.maturity,
  };
}
