import { describe, expect, it } from "vitest";
import { calculateChart } from "./jyotish";
import { executeRule, executableRuleSchema, resolveRuleFact } from "./ruleDsl";

const chart = calculateChart({ name:"Rule",date:"1990-05-17",time:"10:30",place:"Hyderabad",latitude:17.385,longitude:78.4867,timezone:"Asia/Kolkata",timezoneOffset:5.5,language:"en",methodology:"parashari",focus:"career",birthTimeAccuracyMinutes:5 });
describe("rule DSL",()=>{
  it("validates, executes and exposes facts",()=>{const lord=(["Mars","Venus","Mercury","Moon","Sun","Mercury","Venus","Mars","Jupiter","Saturn","Saturn","Jupiter"] as const)[(chart.placements.find(p=>p.name==="Lagna")!.sign+9)%12],rule=executableRuleSchema.parse({id:"career-lord",version:1,sourceKey:"judgment:career:house-lord",tradition:"parashari",topic:"career",effect:"support",weight:10,condition:{type:"predicate",fact:{kind:"house-lord",house:10},operator:"eq",value:lord},exceptions:[],interpretation:"The configured tenth lord is identified.",harmClass:"general-cultural",reviewStatus:"draft"});const result=executeRule(chart,rule,"2026-08-30T00:00:00.000Z");expect(result.matched).toBe(true);expect(result.facts[0].value).toBe(lord);expect(result.publishable).toBe(false);});
  it("applies cancellation exceptions",()=>{const result=executeRule(chart,{id:"cancel",version:1,sourceKey:"test",tradition:"parashari",topic:"career",effect:"support",weight:20,condition:{type:"predicate",fact:{kind:"planet-house",planet:"Sun"},operator:"gte",value:1},exceptions:[{id:"always",condition:{type:"predicate",fact:{kind:"planet-house",planet:"Sun"},operator:"gte",value:1},effect:"cancel",factor:.5}],interpretation:"Fixture",harmClass:"general-cultural",reviewStatus:"approved"},"2026-08-30T00:00:00.000Z");expect(result.matched).toBe(true);expect(result.effectiveWeight).toBe(0);expect(result.appliedExceptions).toHaveLength(1);});
  it("resolves book-rule facts for Panchanga, Avastha, relationship, aspect and Ashtakavarga",()=>{const iso="2026-08-30T00:00:00.000Z",refs=[{kind:"panchanga-limb",limb:"tithi"},{kind:"natal-panchanga-tithi-class"},{kind:"natal-panchanga-tattva-conflict",first:"Vara",second:"Tithi"},{kind:"planet-balaadi-avastha",planet:"Sun"},{kind:"relationship-compound",from:"Sun",to:"Moon"},{kind:"graha-aspect",from:"Saturn",to:"Moon"},{kind:"sarvashtakavarga-sign",sign:0},{kind:"planet-nakshatra",planet:"Moon"}]as const;for(const ref of refs)expect(resolveRuleFact(chart,ref,iso)).not.toBeUndefined();});
});
