import type { ChartResult, GrahaName } from "./schema";
import { jdToIso, isoToJd } from "./dashaCalendar";
import { calculateDoshas } from "./doshas";

const LORDS:GrahaName[]=["Mars","Venus","Mercury","Moon","Sun","Mercury","Venus","Mars","Jupiter","Saturn","Saturn","Jupiter"],MALEFICS=new Set<GrahaName>(["Sun","Mars","Saturn","Rahu","Ketu"]),KENDRAS=new Set([1,4,7,10]),TRIKONAS=new Set([1,5,9]),DHANA_HOUSES=new Set([2,5,9,11]);
const house=(origin:number,target:number)=>((target-origin+12)%12)+1,angular=(a:number,b:number)=>{const d=Math.abs(a-b)%360;return Math.min(d,360-d);};
type Pattern={id:string;label:string;polarity:"challenging"|"supportive";strength:number;involvedPlanets:string[];involvedHouses:number[];evidence:string[];sourceKey:string;reviewStatus:"draft-unreviewed"};

export function detectSynthesisPatterns(chart:ChartResult){
  const lagna=chart.placements.find((item)=>item.name==="Lagna")!,patterns:Pattern[]=[],planet=(name:string)=>chart.placements.find((item)=>item.name===name)!,aspects=(a:string,b:string)=>chart.advanced.aspects.some((item)=>item.from===a&&item.to===b),associated=(a:string,b:string)=>planet(a).sign===planet(b).sign||aspects(a,b)||aspects(b,a),lordOf=(h:number)=>LORDS[(lagna.sign+h-1)%12];
  for(let targetHouse=1;targetHouse<=12;targetHouse++){const sign=(lagna.sign+targetHouse-1)%12,before=(sign+11)%12,after=(sign+1)%12,left=chart.placements.filter((item)=>MALEFICS.has(item.name)&&item.sign===before),right=chart.placements.filter((item)=>MALEFICS.has(item.name)&&item.sign===after);if(left.length&&right.length)patterns.push({id:`papakartari-house-${targetHouse}`,label:`Papakartari enclosure around house ${targetHouse}`,polarity:"challenging",strength:Math.min(1,.45+.12*(left.length+right.length)),involvedPlanets:[...left,...right].map((item)=>item.name),involvedHouses:[targetHouse],evidence:[`${left.map((item)=>item.name).join(", ")} in preceding sign`,`${right.map((item)=>item.name).join(", ")} in following sign`],sourceKey:"synthesis:papakartari",reviewStatus:"draft-unreviewed"});}
  for(const luminary of ["Sun","Moon"] as const){const node=["Rahu","Ketu"].map(planet).sort((a,b)=>angular(luminary==="Sun"?planet("Sun").longitude:planet("Moon").longitude,a.longitude)-angular(luminary==="Sun"?planet("Sun").longitude:planet("Moon").longitude,b.longitude))[0],orb=angular(planet(luminary).longitude,node.longitude);if(orb<=12)patterns.push({id:`grahan-${luminary.toLowerCase()}`,label:`${luminary}-node Grahan candidate`,polarity:"challenging",strength:Math.max(.25,1-orb/15),involvedPlanets:[luminary,node.name],involvedHouses:[house(lagna.sign,planet(luminary).sign)],evidence:[`${luminary} and ${node.name} separated by ${orb.toFixed(2)}°`],sourceKey:"synthesis:grahan",reviewStatus:"draft-unreviewed"});}
  const moonSaturnOrb=angular(planet("Moon").longitude,planet("Saturn").longitude);if(planet("Moon").sign===planet("Saturn").sign||aspects("Saturn","Moon"))patterns.push({id:"vish-moon-saturn",label:"Moon–Saturn Vish candidate",polarity:"challenging",strength:planet("Moon").sign===planet("Saturn").sign?Math.max(.45,1-moonSaturnOrb/30):.45,involvedPlanets:["Moon","Saturn"],involvedHouses:[house(lagna.sign,planet("Moon").sign)],evidence:[planet("Moon").sign===planet("Saturn").sign?`Moon and Saturn share a sign (${moonSaturnOrb.toFixed(2)}° separation)`:"Saturn has Graha Drishti to Moon"],sourceKey:"synthesis:vish",reviewStatus:"draft-unreviewed"});
  const restrictiveHouses=[6,8,12],restrictionEvidence=restrictiveHouses.flatMap((h)=>{const sign=(lagna.sign+h-1)%12,occupants=chart.placements.filter((item)=>MALEFICS.has(item.name)&&item.sign===sign);return occupants.map((item)=>({house:h,planet:item.name}));}),restrictionLords=restrictiveHouses.map((h)=>lordOf(h)),restrictionAssociations=restrictionLords.filter((lord,index)=>restrictionLords.some((other,j)=>j!==index&&associated(lord,other)));if(restrictionEvidence.length>=2||restrictionAssociations.length>=2)patterns.push({id:"restriction-cluster",label:"Restriction/isolation structural cluster",polarity:"challenging",strength:Math.min(1,.25*restrictionEvidence.length+.15*new Set(restrictionAssociations).size),involvedPlanets:[...new Set([...restrictionEvidence.map((item)=>item.planet),...restrictionAssociations])],involvedHouses:restrictiveHouses,evidence:[...restrictionEvidence.map((item)=>`${item.planet} occupies house ${item.house}`),...(restrictionAssociations.length?[`6th/8th/12th lords associated: ${[...new Set(restrictionAssociations)].join(", ")}`]:[])],sourceKey:"synthesis:restriction-cluster",reviewStatus:"draft-unreviewed"});
  const yogaPairs=(first:Set<number>,second:Set<number>,id:string,label:string,sourceKey:string)=>{const pairs=[];for(const a of first)for(const b of second){const la=lordOf(a),lb=lordOf(b);if(la!==lb&&associated(la,lb))pairs.push({a,b,la,lb});}if(pairs.length)patterns.push({id,label,polarity:"supportive",strength:Math.min(1,.4+.12*pairs.length),involvedPlanets:[...new Set(pairs.flatMap((item)=>[item.la,item.lb]))],involvedHouses:[...new Set(pairs.flatMap((item)=>[item.a,item.b]))],evidence:pairs.map((item)=>`House ${item.a} lord ${item.la} associates with house ${item.b} lord ${item.lb}`),sourceKey,reviewStatus:"draft-unreviewed"});};
  yogaPairs(KENDRAS,TRIKONAS,"raja-yoga-cluster","Raja Yoga association cluster","synthesis:raja-yoga");yogaPairs(DHANA_HOUSES,DHANA_HOUSES,"dhana-yoga-cluster","Dhana Yoga association cluster","synthesis:dhana-yoga");
  for(const dosha of calculateDoshas(chart).patterns.filter((item)=>item.detected))patterns.push({id:`dosha-${dosha.id}`,label:dosha.label,polarity:"challenging",strength:dosha.severity==="high"?1:dosha.severity==="moderate"?.7:dosha.severity==="low"?.4:.15,involvedPlanets:dosha.id==="mangal"?["Mars"]:[],involvedHouses:dosha.id==="mangal"?(dosha.evidence as Array<{house:number;triggered:boolean}>).filter((item)=>item.triggered).map((item)=>item.house):[],evidence:[`Dosha engine raw severity ${dosha.rawSeverity}; effective severity ${dosha.severity}`,`${dosha.cancellationsOrMitigations.length} cancellation/mitigation observations`],sourceKey:String(dosha.sourceKey),reviewStatus:"draft-unreviewed"});
  return patterns.sort((a,b)=>b.strength-a.strength);
}

const THEME_DEFS=[{id:"restriction-isolation",label:"Restriction, isolation or institutional pressure",houses:[6,8,12],planets:["Saturn","Rahu","Ketu"],patterns:["restriction","papakartari","kemadruma","kaal-sarpa","vish"]},{id:"authority-conflict",label:"Authority, rules or conflict pressure",houses:[6,8,10],planets:["Sun","Mars","Saturn"],patterns:["restriction","papakartari"]},{id:"career-responsibility",label:"Work, responsibility and public role",houses:[6,10,11],planets:["Sun","Saturn","Mercury"],patterns:["raja-yoga"]},{id:"relationships-agreements",label:"Relationships and agreements",houses:[2,7,11],planets:["Venus","Jupiter"],patterns:[]},{id:"resources-growth",label:"Resources, learning and growth",houses:[2,5,9,11],planets:["Jupiter","Venus","Mercury"],patterns:["dhana-yoga"]},{id:"transition-withdrawal",label:"Transition, endings or withdrawal",houses:[8,12],planets:["Rahu","Ketu","Saturn"],patterns:["grahan","kemadruma"]}] as const;

export function detectLifeThemes(chart:ChartResult,startIso:string,endIso:string){
  const start=isoToJd(startIso),end=isoToJd(endIso);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)throw new Error("Invalid date range");const lagna=chart.placements.find((item)=>item.name==="Lagna")!,patterns=detectSynthesisPatterns(chart),owned=(name:string)=>LORDS.flatMap((lord,index)=>lord===name?[house(lagna.sign,index)]:[]),placementHouse=(name:string)=>house(lagna.sign,planet(name).sign);function planet(name:string){return chart.placements.find((item)=>item.name===name)!;}
  const periods=chart.advanced.vimshottariTimeline.flatMap((maha)=>maha.subPeriods.map((antar)=>({mahadasha:maha.lord,antardasha:antar.lord,startJulianDay:Math.max(start,antar.startJulianDay),endJulianDay:Math.min(end,antar.endJulianDay)}))).filter((item)=>item.endJulianDay>item.startJulianDay).map((period)=>{const activatedPlanets=[period.mahadasha,period.antardasha],activatedHouses=[...new Set(activatedPlanets.flatMap((name)=>[placementHouse(name),...owned(name)]))],activatedPatterns=patterns.filter((pattern)=>pattern.involvedPlanets.some((name)=>activatedPlanets.includes(name))||pattern.involvedHouses.some((h)=>activatedHouses.includes(h)));const themes=THEME_DEFS.map((theme)=>{const houseHits=theme.houses.filter((h)=>activatedHouses.includes(h)),planetHits=theme.planets.filter((p)=>activatedPlanets.includes(p)),patternHits=activatedPatterns.filter((pattern)=>theme.patterns.some((token)=>pattern.id.includes(token))),raw=15*houseHits.length+12*planetHits.length+patternHits.reduce((sum,item)=>sum+item.strength*30,0),score=Math.min(100,Math.round(raw));return{id:theme.id,label:theme.label,score,confidence:{score:Number((Math.min(.75,.2+score/200)).toFixed(2)),status:"heuristic-not-calibrated",factors:["No blind outcome calibration yet","No approved interpretive rules yet"]},reasons:[...houseHits.map((h)=>`Dasha lords activate house ${h}`),...planetHits.map((p)=>`${p} is an active Dasha lord`),...patternHits.map((p)=>`Activates ${p.label} (${p.strength.toFixed(2)})`)],sourceKeys:[...new Set(patternHits.map((p)=>p.sourceKey))]};}).filter((theme)=>theme.score>0).sort((a,b)=>b.score-a.score);return{mahadasha:period.mahadasha,antardasha:period.antardasha,startIso:jdToIso(period.startJulianDay),endIso:jdToIso(period.endJulianDay),activatedPlanets,activatedHouses,activatedPatterns:activatedPatterns.map((item)=>item.id),themes};});
  return{schemaVersion:"sahadeva-life-themes-1",range:{startIso:jdToIso(start),endIso:jdToIso(end)},patterns,periods,sourceCoverage:{status:"awaiting-reviewed-rules",approvedCitations:[],unresolvedSourceKeys:[...new Set(patterns.map((item)=>item.sourceKey))]},uncertainty:{confidenceStatus:"heuristic-not-calibrated",blindValidationCompleted:false,notice:"Scores rank structural activation inside this chart only. They are not event probabilities and must not be compared as calibrated risks."},safety:{status:"research-preview",prohibitedInferences:["criminal conduct","arrest or imprisonment","court outcome","medical diagnosis","death or lifespan"],notice:"Restriction themes may describe many experiences, including demanding work, caregiving, illness-related isolation, institutional routines or voluntary retreat. They do not predict a legal event."}};
}
