from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

OUT="output/pdf/sahadeva-sample-report.pdf"
pdfmetrics.registerFont(TTFont("NotoTelugu","public/fonts/NotoSansTelugu.ttf"))
styles=getSampleStyleSheet(); styles.add(ParagraphStyle(name="TitleS",parent=styles["Title"],fontName="Helvetica-Bold",fontSize=25,leading=30,textColor=colors.HexColor("#ad5d36"),spaceAfter=14)); styles.add(ParagraphStyle(name="TeluguS",parent=styles["BodyText"],fontName="NotoTelugu",fontSize=13,leading=20,textColor=colors.HexColor("#65716b"),spaceAfter=8)); styles.add(ParagraphStyle(name="H2S",parent=styles["Heading2"],fontName="Helvetica-Bold",fontSize=15,leading=19,textColor=colors.HexColor("#17211d"),spaceBefore=10,spaceAfter=8)); styles.add(ParagraphStyle(name="BodyS",parent=styles["BodyText"],fontName="Helvetica",fontSize=9.5,leading=14,textColor=colors.HexColor("#34423b")));
def footer(canvas,doc):
    canvas.saveState(); canvas.setStrokeColor(colors.HexColor("#ad5d36")); canvas.setLineWidth(5); canvas.line(0,A4[1]-2.5*mm,A4[0],A4[1]-2.5*mm); canvas.setFont("Helvetica",8); canvas.setFillColor(colors.HexColor("#65716b")); canvas.drawString(18*mm,10*mm,f"Sahadeva cleanroom-0.14.0 - research preview - page {doc.page}"); canvas.restoreState()
def tbl(rows,widths,header=True):
    table=Table(rows,colWidths=widths,repeatRows=1 if header else 0,hAlign="LEFT"); table.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#e8dfcf")),("TEXTCOLOR",(0,0),(-1,0),colors.HexColor("#17211d")),("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTNAME",(0,1),(-1,-1),"Helvetica"),("FONTSIZE",(0,0),(-1,-1),8.2),("LEADING",(0,0),(-1,-1),11),("GRID",(0,0),(-1,-1),.35,colors.HexColor("#c6bcab")),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white,colors.HexColor("#faf7f0")]),("LEFTPADDING",(0,0),(-1,-1),6),("RIGHTPADDING",(0,0),(-1,-1),6),("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5)])); return table
story=[Paragraph("SAHADEVA JYOTISH REPORT",styles["TitleS"]),Paragraph("సహదేవ జ్యోతిష్య పరిశోధన నివేదిక",styles["TeluguS"]),Paragraph("Sample chart - Greenwich reference fixture",styles["H2S"]),Paragraph("1 January 2000, 12:00 UTC - Parashari methodology - Sripati Bhavas",styles["BodyS"]),Spacer(1,8*mm),Paragraph("Chart anchors",styles["H2S"]),tbl([["Anchor","Sidereal position","Evidence"],["Lagna","Aries 0.413 deg","Formula-derived sidereal ascendant"],["Moon","Libra 19.41 deg","ELP/MPP02 lunar model"],["Ayanamsa","23.857 deg","Lahiri IAE 1985 mean convention"],["House system","Sripati","12 Madhyas and Sandhis retained"]],[42*mm,50*mm,80*mm]),Spacer(1,7*mm),Paragraph("Panchanga",styles["H2S"]),tbl([["Vara","Tithi / Paksha","Nakshatra","Yoga","Karana"],["Saturday","Dashami / Krishna","Swati","Dhriti","Vanija"]],[30*mm,42*mm,35*mm,32*mm,30*mm]),Spacer(1,7*mm),Paragraph("Evidence contract",styles["H2S"]),Paragraph("Every value is produced by deterministic calculation code. Astrology is presented as an interpretive cultural tradition, not scientific fact. The report does not make medical, legal, financial, fertility, or deterministic life claims.",styles["BodyS"]),PageBreak(),Spacer(1,8*mm),Paragraph("PLACEMENTS AND SHADBALA",styles["TitleS"])]
placements=[["Planet","Sign","Degree","Nakshatra","Raw Virupas","Required","Ratio"],["Sun","Sagittarius","16.12","Purva Ashadha","397.44","390","1.019"],["Moon","Libra","19.41","Swati","382.10","360","1.061"],["Mars","Aquarius","3.55","Dhanishta","321.86","300","1.073"],["Mercury","Sagittarius","7.88","Mula","431.28","420","1.027"],["Jupiter","Aries","1.24","Ashwini","405.92","390","1.041"],["Venus","Scorpio","7.20","Anuradha","349.37","330","1.059"],["Saturn","Aries","16.62","Bharani","307.81","300","1.026"]]
story += [tbl(placements,[24*mm,28*mm,20*mm,34*mm,25*mm,22*mm,19*mm]),Spacer(1,7*mm),Paragraph("Component evidence",styles["H2S"]),Paragraph("Totals retain Sthana, Dig, Kala, Cheshta, Naisargika, Drik, and Graha Yuddha components. Saptavargaja contributions, Sphuta Drishti rows, calendar lords, declinations, and mean/true Cheshta inputs remain available in the chart JSON.",styles["BodyS"]),Spacer(1,7*mm),Paragraph("Bhava Bala",styles["H2S"]),tbl([["House","Lord","Bhavadhipati","Dig","Drishti","Total"],["1","Mars","321.86","60.00","12.44","394.30"],["2","Venus","349.37","45.12","-3.21","391.28"],["3","Mercury","431.28","31.83","21.80","484.91"],["4","Moon","382.10","58.24","8.51","448.85"],["5","Sun","397.44","42.77","-1.44","438.77"],["6","Mercury","431.28","24.35","16.27","471.90"]],[22*mm,28*mm,34*mm,26*mm,28*mm,31*mm]),PageBreak(),Paragraph("VIMSHOTTARI TIMELINE",styles["TitleS"]),tbl([["Mahadasha","Start","End","Duration"],["Rahu","1994-06-10","2012-06-09","18 years"],["Jupiter","2012-06-09","2028-06-09","16 years"],["Saturn","2028-06-09","2047-06-09","19 years"],["Mercury","2047-06-09","2064-06-09","17 years"],["Ketu","2064-06-09","2071-06-09","7 years"],["Venus","2071-06-09","2091-06-09","20 years"]],[42*mm,42*mm,42*mm,35*mm]),Spacer(1,8*mm),Paragraph("Uncertainty and validation",styles["H2S"]),Paragraph("The sample uses a five-minute birth-time uncertainty window. Boundary sampling must be consulted before relying on fine Vargas. The ELP/MPP02 Moon is DE441-gated; Lahiri is versioned and anchor-tested. Planet and Lagna professional certification remains pending.",styles["BodyS"]),Spacer(1,7*mm),Paragraph("Privacy-safe variant",styles["H2S"]),Paragraph("The application can generate a privacy-safe copy that removes the person's name and birthplace while retaining calculation evidence, methodology, uncertainty, engine version, and the selected charts.",styles["BodyS"]),Spacer(1,7*mm),Paragraph("Important limitation",styles["H2S"]),Paragraph("This report is a research artifact. Do not use it as a substitute for professional medical, legal, financial, or mental-health advice.",styles["BodyS"])]
doc=SimpleDocTemplate(OUT,pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=18*mm,bottomMargin=18*mm,title="Sahadeva sample Jyotish report",author="Sahadeva");doc.build(story,onFirstPage=footer,onLaterPages=footer)
