import { useEffect, useMemo, useState } from "react";

type Precision="day"|"month"|"year"|"range";
type Topic="career"|"marriage"|"wealth"|"education"|"children"|"property"|"spirituality";
type Event={id:string;topic:Topic;label:string;precision:Precision;date:string;endDate:string;confidence:number};
export type BtrSession={earliestTime:string;latestTime:string;stepMinutes:number;events:Event[]};
type Result={rankedClusters:Array<{startTime:string;endTime:string;bestScore:number;holdoutScore:number|null;candidateCount:number;signature?:string}>;notice:string;diagnostics?:{conclusive:boolean;spread:number;eventCount:number;leaveOneOut:Array<{eventId:string;topRange:string}>}};
const topics:Topic[]=["career","marriage","wealth","education","children","property","spirituality"];
const blank=():Event=>({id:crypto.randomUUID(),topic:"career",label:"",precision:"day",date:"",endDate:"",confidence:4});

export function BtrWorkspace({profile,onClose,language}:{profile:{time:string;[key:string]:unknown};onClose:()=>void;language:"en"|"te"}){
 const key="sahadeva.btr.session",[session,setSession]=useState<BtrSession>(()=>{try{return JSON.parse(localStorage.getItem(key)||"") as BtrSession}catch{return{earliestTime:profile.time,latestTime:profile.time,stepMinutes:5,events:[blank(),blank(),blank()]}}}),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const te=language==="te",valid=useMemo(()=>session.events.length>=3&&session.events.length<=8&&session.earliestTime<=session.latestTime&&session.events.every(e=>e.label.trim()&&e.date&&(e.precision!=="range"||e.endDate)),[session]);
 useEffect(()=>{localStorage.setItem(key,JSON.stringify(session));void fetch("/api/btr/session",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({session})}).catch(()=>{})},[session]);
 useEffect(()=>{void fetch("/api/btr/session").then(r=>r.ok?r.json():null).then(data=>data?.session&&setSession(data.session)).catch(()=>{});void fetch("/api/btr/telemetry",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"opened"})}).catch(()=>{})},[]);
 const update=(id:string,patch:Partial<Event>)=>setSession(s=>({...s,events:s.events.map(e=>e.id===id?{...e,...patch}:e)}));
 const run=async()=>{setBusy(true);setError("");setResult(null);const r=await fetch("/api/btr/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({session,profile})});const data=await r.json() as Result&{error?:string};if(!r.ok)setError(data.error||"BTR could not be calculated");else setResult(data);setBusy(false)};
 const restart=()=>{const next={earliestTime:profile.time,latestTime:profile.time,stepMinutes:5,events:[blank(),blank(),blank()]};setSession(next);setResult(null);void fetch("/api/btr/telemetry",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"restarted"})})};
 const close=()=>{void fetch("/api/btr/telemetry",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:result?"closed_after_result":"abandoned",eventCount:session.events.filter(event=>event.label).length})});onClose()};
 return <div className="btr-overlay" role="dialog" aria-modal="true"><section className="btr-workspace"><header><div><span>BTR</span><h2>{te?"జనన సమయ సవరణ":"Birth-time rectification"}</h2><p>{te?"3–8 నిర్ధారిత జీవిత సంఘటనలను సమీక్షించండి.":"Review 3–8 confirmed events before calculating. Approximate dates stay explicitly approximate."}</p></div><button onClick={close} aria-label="Close">✕</button></header>
 <div className="btr-range"><label>{te?"మొదటి సమయం":"Earliest birth time"}<input type="time" value={session.earliestTime} onChange={e=>setSession(s=>({...s,earliestTime:e.target.value}))}/></label><label>{te?"చివరి సమయం":"Latest birth time"}<input type="time" value={session.latestTime} onChange={e=>setSession(s=>({...s,latestTime:e.target.value}))}/></label><label>{te?"దశ":"Step"}<select value={session.stepMinutes} onChange={e=>setSession(s=>({...s,stepMinutes:+e.target.value}))}><option value="1">1 min</option><option value="5">5 min</option><option value="10">10 min</option></select></label></div>
 <div className="btr-events">{session.events.map((event,index)=><article key={event.id}><strong>{te?"సంఘటన":"Event"} {index+1}</strong><label>{te?"రకం":"Type"}<select value={event.topic} onChange={e=>update(event.id,{topic:e.target.value as Topic})}>{topics.map(t=><option key={t}>{t}</option>)}</select></label><label>{te?"ఏమి జరిగింది?":"What happened?"}<input value={event.label} onChange={e=>update(event.id,{label:e.target.value})} placeholder={te?"ఉదా: కొత్త ఉద్యోగం":"e.g. Started a new job"}/></label><label>{te?"తేదీ ఖచ్చితత్వం":"Date precision"}<select value={event.precision} onChange={e=>update(event.id,{precision:e.target.value as Precision,endDate:""})}><option value="day">Exact day</option><option value="month">Month only</option><option value="year">Year only</option><option value="range">Date range</option></select></label><label>{te?"తేదీ":"Date"}<input type={event.precision==="year"?"number":event.precision==="month"?"month":"date"} min={event.precision==="year"?"1900":undefined} max={event.precision==="year"?String(new Date().getFullYear()):undefined} value={event.date} onChange={e=>update(event.id,{date:e.target.value})}/></label>{event.precision==="range"&&<label>End date<input type="date" value={event.endDate} onChange={e=>update(event.id,{endDate:e.target.value})}/></label>}<label>Confidence <select value={event.confidence} onChange={e=>update(event.id,{confidence:+e.target.value})}>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v}/5</option>)}</select></label><button className="danger" disabled={session.events.length<=3} onClick={()=>setSession(s=>({...s,events:s.events.filter(e=>e.id!==event.id)}))}>{te?"తొలగించు":"Remove"}</button></article>)}</div>
 {session.events.length<8&&<button onClick={()=>setSession(s=>({...s,events:[...s.events,blank()]}))}>+ {te?"సంఘటన జోడించండి":"Add event"}</button>}
 <div className="btr-actions"><button onClick={restart}>{te?"మళ్లీ ప్రారంభించు":"Restart"}</button><button onClick={close}>{te?"రద్దు":"Cancel"}</button><button className="primary" disabled={!valid||busy} onClick={run}>{busy?"Calculating…":te?"BTR లెక్కించండి":"Review complete · Run BTR"}</button></div>{error&&<p className="chat-error">{error}</p>}
 {result&&<section className="btr-result"><h3>{result.diagnostics?.conclusive?"Candidate ranges":"Inconclusive result"}</h3>{result.rankedClusters.slice(0,5).map((r,i)=><p key={r.startTime}><strong>{i+1}. {r.startTime}–{r.endTime}</strong> · score {r.bestScore} · validation {r.holdoutScore??"—"}<small>{r.signature?` Chart signature ${r.signature}.`:""} This range ranked by agreement between dated events and timing activation.</small></p>)}{result.diagnostics&&!result.diagnostics.conclusive&&<p>The leading candidates are too close to separate reliably. Add a precisely dated, independent event or narrow the birth-time range.</p>}<details><summary>Stability check</summary>{result.diagnostics?.leaveOneOut.map(x=><p key={x.eventId}>Without {x.eventId}: {x.topRange}</p>)}</details><small>{result.notice}</small></section>}
 </section></div>
}
